enyo.depends(
     "EditDialog.js",
     "EditContent.js",
     "NotebookDialog.js",
     "CreateNotebookDialog.js",
     "TagDialog.js",
     "CreateTagDialog.js",
     "CreateListItemDialog.js",
     "EditListItemDialog.js",
     "RatingDialog.js",
     "AlarmDialog.js",
     "AddToShoppingListDialog.js"
); 