function lang(a){if(langid==-1)return lng[0][a].message;return lng[langid][a].message}links=[["indexp","id0",-1,-1,-1],["friends","friends?section=all_requests",0,1,0],["photos","albums",0,0,0],["videos","video?section=tagged",0,0,0],["messages","mail?filter=new",0,1,1],["notes","notes.php?act=comms",0,1,0],["groups","groups",0,1,0],["news","feed",-1,-1,-1],["comments","feed?section=comments",-1,-1,-1]];ActiveTabID=0;langid=-1;UpdateTimer=oldMessages=oldTotal=0;loadLng(langid);
if(cfg("music","true")=="1")localStorage.music="true";var msver;try{msver=chrome.app.getDetails().version}catch(e$$5){msver="err"}function cfg(a,c){if(localStorage[a]==undefined&&c!=undefined)localStorage[a]=c;return localStorage[a]}try{var audioObj=new Audio("");audioObj.src="http://vkontakte.ru/mp3/chat_sound.mp3";audioObj.id="chat_sound";audioObj.load()}catch(e$$6){console.log(e$$6.message)}
function setIcon(a){a=parseInt(a);if(isNaN(a))a=0;chrome.browserAction.setIcon({path:"/icon/"+a+"_48.png"});localStorage.icon=a}function getiUrl(){}function loadLng(a){if(a==-1){a=parseInt(localStorage.lang);if(a==undefined||isNaN(a))a=0}if(langid!=a){langid=a;localStorage.lang=a}}function addobj(a,c,b,d){a=document.createElement(a);a.setAttribute("type",b);c&&a.setAttribute("id",c);a.setAttribute("src",d);document.head.appendChild(a)}
function ge(){for(var a,c=0;c<arguments.length;c++){var b=arguments[c];if(typeof b=="string")b=document.getElementById(b);if(arguments.length==1)return b;a||(a=[]);a.push(b)}return a}
function geByClass(a,c,b){var d=[];if(c==null)c=document;if(b==null)b="*";if(c.getElementsByClassName){d=c.getElementsByClassName(a);if(b!="*")for(i=0;i<d.length;i++)d.nodeName==b&&d.splice(i,1);return d}c=c.getElementsByTagName(b);b=c.length;a=RegExp("(^|\\s)"+a+"(\\s|$)");for(j=i=0;i<b;i++)if(a.test(c[i].className)){d[j]=c[i];j++}return d}
function $c(a,c){if(a=="#text"||a=="#")return document.createTextNode(c);else if(typeof a=="string"&&a.substr(0,1)=="#")return document.createTextNode(a.substr(1));else var b=document.createElement(a);for(var d in c)if(d=="kids")for(var e in c[d])typeof c[d][e]=="object"&&b.appendChild(c[d][e]);else if(d=="#text")b.appendChild(document.createTextNode(c[d]));else if(d=="#html")b.innerHTML=c[d];else b.setAttribute(d,c[d]);return b}
function reCalcTotal(a){var c=0;if(!a)for(i in links)if(links[i][2]!=-1)if(localStorage[links[i][0]]!="false")c+=links[i][2];showEventsCount(c);if(cfg("music","true")=="true"){oldTotal<c&&audioObj.play();oldTotal=c}if(cfg("notify","true")=="true"){oldMessages<links[4][2]&&webkitNotifications.createHTMLNotification("/notify.html").show();oldMessages=links[4][2]}}
function $q(a,c){var b=a.params?a.params:[],d=new XMLHttpRequest;d.onreadystatechange=function(e){e=e.target;if(e.readyState==4&&c){var f=e.getAllResponseHeaders().split("\r\n");c({status:e.status,responseText:e.responseText,headers:f})}};d.open(a.method,a.url);for(i in b.head)d.setRequestHeader(i,b.head[i]);for(i in b.mime)d.overrideMimeType(b.mime[i]);b.post&&d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");if(b.post||b.xml)d.setRequestHeader("X-Requested-With","XMLHttpRequest");
if(typeof b.post=="object"){x=b.post;b.post="";for(i in x)b.post+=i+"="+x[i]+"&"}d.send(b.post)}function setUpdateTimer(){UpdateTimer&&clearTimeout(UpdateTimer);var a=parseInt(localStorage.checktime);if(a<10||isNaN(a)){a=10;localStorage.checktime=10}UpdateTimer=setTimeout(checkForNew,a*1E3)}
function checkForNew(){if(localStorage.active=="false"){reCalcTotal(true);return true}$q({method:"GET",url:getMainUrl()+"feed2.php"},function(a){if(a.status==200)if(a=JSON.parse(a.responseText)){localStorage.vkid=a.user.id;for(i in links)if(links[i][2]!=-1){cnt=a[links[i][0]].count;links[i][2]=cnt}reCalcTotal()}});setUpdateTimer()}checkForNew();function checkForNewNotNow(a){a||(a=5E3);setTimeout("checkForNew()",a)}function getMainUrl(){return"http://"+cfg("vkurl","vkontakte.ru")+"/"}
function showEventsCount(a){if(a==0)chrome.browserAction.setBadgeText({text:""});else{chrome.browserAction.setBadgeBackgroundColor({color:[200,50,50,255]});chrome.browserAction.setBadgeText({text:a.toString()})}}function fixfUpdate(){if(localStorage.xvk){localStorage["xvk"+localStorage.vkid]=localStorage.xvk;localStorage.xvk=""}}
function initVal(a,c,b){if(a.substr(0,1)=="!"){a=a.substr(1);if(localStorage.vkid){a=="xvk"&&fixfUpdate();a+=localStorage.vkid}}if(b!=undefined)localStorage[a]=b;else c(localStorage[a])}function initCS(a,c){loadLng(parseInt(a.lang));var b=a.url.match(/([^.\/]+\.(ru|com))/g);if(b&&b[0]){if(b[0].indexOf("vk")==-1)return;localStorage.vkurl=b[0]}c(msver)}function getSesid(a){chrome.cookies.get({url:"http://durov.ru",name:"sid"},a)}localStorage.theme&&chrome.tabs.create({url:"themes.html#update"});
function domute(){localStorage.notify=false;localStorage.music=false}
chrome.extension.onRequest.addListener(function(a,c,b){if(c.id!="pfmipnglcoeahcdfnedagnegoifnjmec"&&c.id!="hanjiajgnonaobdlklncdjdmpbomlhoa"&&c.id!="gafanfkfmgjeibehakfafmfclnhdgnek"&&c.id!="oppioiiceobdjaplainofeechdibnkcc"){console.log("fail");return b(false)}if(a.action=="xss")$q(a,b);else if(a.action=="getval")initVal(a.name,b);else if(a.action=="setval")initVal(a.name,b,a.variable);else if(a.action=="initcs")initCS(a.variable,b);else if(a.action=="eval")eval(a.variable);else if(a.action=="sidit")getSesid(b);
else if(a.action=="update")checkForNew();else if(a.action=="update2")checkForNewNotNow();else a.action=="mute"?domute():b(false)});setIcon(cfg("icon",0));
