[ids]
*

[global]
default_layout = workman

[main]
rightalt = layer(workspaces)
capslock = backspace
leftalt = layer(control)
leftcontrol = layer(meta)
leftmeta = layer(alt)

[workspaces]
f = kp1
d = kp2
s = kp3
a = kp4
q = kp5
w = kp6
e = kp7
r = kp8

[control:C]
space = setlayout(ru)

[ru_control:C]
space = setlayout(workman)
a = C-a
b = C-v
c = C-m
d = C-h
e = C-r
f = C-t
g = C-g
h = C-y
i = C-u
j = C-n
k = C-e
l = C-o
m = C-l
n = C-k
o = C-p
p = C-semicolon
q = C-q
r = C-w
s = C-s
t = C-b
u = C-f
v = C-c
w = C-d
x = C-x
y = C-j
z = C-z

include layouts/workman

[workman:layout]
p = :

[shift:S]
p = ;

include layouts/ru

[ru_control+ru_shift]
space = setlayout(workman)
a = C-S-a
b = C-S-v
c = C-S-m
d = C-S-h
e = C-S-r
f = C-S-t
g = C-S-g
h = C-S-y
i = C-S-u
j = C-S-n
k = C-S-e
l = C-S-o
m = C-S-l
n = C-S-k
o = C-S-p
p = C-S-semicolon
q = C-S-q
r = C-S-w
s = C-S-s
t = C-S-b
u = C-S-f
v = C-S-c
w = C-S-d
x = C-S-x
y = C-S-j
z = C-S-z

[ru:layout]
leftalt = layer(ru_control)
