[ids]
*

[global]
default_layout = workman

[main]
rightalt = layer(workspaces)
leftalt = layer(control)
leftcontrol = layer(meta)
leftmeta = layer(alt)

[workspaces]
f = kp1
d = kp2
s = kp3
a = kp4
q = kp5
w = kp6
e = kp7
r = kp8

[control:C]
space = setlayout(ru)

[ru_control:C]
space = setlayout(workman)
a = C-a
b = C-v
c = C-m
d = C-h
e = C-r
f = C-t
g = C-g
h = C-y
i = C-u
j = C-n
k = C-e
l = C-o
m = C-l
n = C-k
o = C-p
p = C-semicolon
q = C-q
r = C-w
s = C-s
t = C-b
u = C-f
v = C-c
w = C-d
x = C-x
y = C-j
z = C-z

include layouts/workman
include layouts/ru

[ru:layout]
leftalt = layer(ru_control)
