[ids]
*

[main]
rightalt = layer(workspaces)
leftalt = leftcontrol
leftcontrol = leftmeta
leftmeta = leftalt

[workspaces]
f = kp1
d = kp2
s = kp3
a = kp4
q = kp5
w = kp6
e = kp7
r = kp8

[control]
# w = C-r
# e = C-k
# r = C-e
# t = C-f
# y = C-h
# u = C-i
# i = C-;
# o = C-l
# p = C-o
# d = C-w
# f = C-u
# h = C-d
# j = C-y
# k = C-n
# l = C-m
# ; = C-p
c = C-v
v = C-b
# b = C-t
# n = C-j
# m = C-c
