function addAppDownLink(){if(window.appControls){if(window.summary_links){var a=document.body.innerHTML.match(/(http\:\/\/.*\.zip)/);if(a)a=a[0];else return;var b=location.pathname.match(/app\d+/)||"app"+window.appId;if(b[0])b=b[0];summary_links.appendChild($c("span",{"class":"divider","#text":"|"}));summary_links.appendChild($c("a",{href:a+(b?"?/"+b+".swf":""),"class":"adwbtn","#text":lang("download")}))}flashDw&&$(".adwbtn").dragout()}};function getStdDw(a,b,c,d){var e=c.replace(/\.mp3/,"");a=$c("a",{id:a,href:b+(c?"?/"+c:""),alt:e,download:c,onclick:"event.cancelBubble=true;","class":"downloadbtn",len:d,kids:{0:dwLoadBtn()}});a.onmouseover=function(){this.onmouseover=function(){};getRemoteFileSize(this.href||this.getAttribute("href"),this)};return a}function getFlashDw(){}var firstaudioid;
function dwmouseover(a){vkevaljs('showTooltip(ge("'+a.id+'"), {text: "'+lang("download")+'", showdt: 0, black: 1, shift: [9, 5, 0]});animate(ge("'+a.id+'"), {opacity: 1}, 200);')}function dwmouseout(a){vkevaljs('animate(ge("'+a.id+'"), {opacity: 0.4}, 200)')}
function newAudioDownLink(){var a=false;$('input[id^="audio_info"],.play').each(function(){var b=$(this);if(!b.attr("parsed")){b.attr("parsed",1);var c=b.attr("id").substr(4);if(c.substr(0,1)=="o"){var d=b.attr("value");c=c.substr(6)}else d=b.siblings(":eq(0)").attr("value");if(!(!d||d.indexOf(",")==-1)){d=d.split(",");var e=d[1];d=d[0];b=b.parent().siblings(":eq(0)");var f=$(".audio_title_wrap,.title_wrap",b);$(".duration",b).text();f=$("b",f).text().trim();var m=$("span[id^='title'],span.title",
b).text().trim();if(f=f+" - "+m)f+=".mp3";d=getStdDw(c,d,f,e);e=$(".actions",b);if(e.length){if(b[0].tagName[0]!="T"){f=$c("div",{"class":"msaudioinfo",id:c+"x",style:"margin-left: 33px;","#html":"&nbsp;"});insertAfter(b[0],f)}else{f=$c("tr",{kids:{0:$c("td"),1:$c("div",{"class":"title_wrap",kids:{0:$c("td",{"class":"msaudioinfo iatwall",id:c+"x","#html":"&nbsp;"})}})}});insertAfter(b[0].parentNode,f)}f=$c("div",{"class":"actdown",kids:{0:$c("div",{"class":"actdownwrap",kids:{0:d}})}});e.append(f)}else if(b[0].tagName[0]!=
"T"){f=$c("div",{"class":"msaudioinfo",id:c+"x"});insertAfter(b[0],f);d=$c("div",{"class":"msaudio",kids:{0:d}});insertAfter(b[0],d)}else{f=$c("tr",{kids:{0:$c("td",{"class":"msaudio",kids:{0:d}}),1:$c("td",{"class":"msaudioinfo iatwall",id:c+"x"})}});insertAfter(b[0].parentNode,f)}$("#audio"+c).bind("click",function(){ge(this.id.substr(5)).onmouseover()});firstaudioid||(firstaudioid="audio"+c);a=true}}});return a}var curAudioId;
function checkCurAudios(){var a=$(".audio.current").attr("id");if(curAudioId!=a)(curAudioId=a)&&$("#"+a+" .downloadbtn")[0].onmouseover()}
function addAudioDownLink(){try{aud_salt=VK().aud_salt}catch(a){}var b=false;$(".playimg").each(function(){var c=$(this);if(!c.attr("parsed")){c.attr("parsed",1);var d=this.id;if(d.substr(2)!="vk"){var e=d+"db";d=c.parent();var f=d.parent();try{var m=c[0].getAttribute("onclick")+""}catch(k){console.log("Fucking error =/")}if(m!="null")if(!(!m||m.indexOf("operate(")==-1)){if(m=m.match(/operate\((.*)\)/))m=m[0];if(m)m=m.split(",");if(m[0]&&m[1]){if(m.length==3){if(m[0].indexOf("'")==-1)return;c=m[0].split("'")[1];
m=m[1].split("'")[1]}else{if(m[3].indexOf("'")==-1)return;c=m[0];var p=m[1],v=m[2],o=m[3].split("'")[1];m=""}if(c.indexOf("(")!=-1)c=c.split("(")[1];m||(m="http://cs"+p+".vkontakte.ru/u"+fixUrlUserId(v)+"/audio/"+o+".mp3");if(c){var n="";if(ge("performer"+c)&&ge("title"+c))n=ge("performer"+c).innerText+" - "+ge("title"+c).innerText;else if(ge("performerWall"+c)&&ge("titleWall"+c))n=ge("performerWall"+c).innerText+" - "+ge("titleWall"+c).innerText;else if(ge("performerChoose"+c)&&ge("titleChoose"+
c))n=ge("performerChoose"+c).innerText+" - "+ge("titleChoose"+c).innerText;if(n)n+=".mp3"}$(".duration",f).attr("id","dur"+e);if(aud_salt)m=decrypt(m,aud_salt);p=getStdDw(e,m,n);insertAfter(f[0].lastElementChild,$c("td",{style:d[0].style.cssText,kids:{0:p}}));b=true}}}}});firstaudioid=false;if(newAudioDownLink()||b){flashDw&&$().dragout&&$(".downloadbtn").each(function(){if(!this.getAttribute("parsed")){this.setAttribute("parsed",1);$(this).dragout()}});firstaudioid&&vksetvar("sorterfixid",firstaudioid);
if(bestAudio)if(window.recommendations||window.album_filters||window.search_filters)swAllBitrate()}}var allSongs=[];
function isAudioDuplicate2(a){var b=$("td.info",a),c=$(".audio_title_wrap,.title_wrap",b);a=$(".duration",b).attr("id","dur"+a.id).text();c=$("b",c).text().trim().toLowerCase();b=$("span.title",b).text().trim().toLowerCase();for(var d=0;d<allSongs.length;d++)if(allSongs[d].dur==a){if(audiodups)return true;if(allSongs[d].art==c&&allSongs[d].title==b)return true}allSongs.push({art:c,title:b,dur:a});return false}
function removeAudioDuplicates(){if($(".audio_filter_selected#album_filtered")[0]||$("#filter_audio.cur_section")[0]){var a=0,b=[];audiodups=_cfg.dupsByTime;if(window.audio_search||window.search_content)$(".audio").each(function(){isAudioDuplicate2(this)&&b.push(this.id)});if(b.length){if(a=b.length){var c="#"+b.join(",#");if(window.audio_search)$(c).remove();else window.search_content&&$(c).parent().remove()}if(a>0){if(!window.dupscounter){c=window.audio_actions||window.summary;c.appendChild($c("span",
{"class":"divider","#text":"|"}));c.appendChild($c("span",{id:"dupscounter"}))}if(window.dupscounter)dupscounter.innerHTML=lang("deldups")+": "+a}allSongs=[]}}}function dwPlayList(a,b){vkvarinvoke("cur.htitle",function(c){vkvarinvoke("cur.audiosIndex.list",function(d){d?dwPlayListReal(a,b,c,d):vkvarinvoke("cur.audios",function(e){dwPlayListReal(a,b,c,e)})})});return false}
function dwPlayListReal(a,b,c,d){var e=a?"":"#EXTM3U\r\n",f=true;if(window.search_input&&search_input.value)b=search_input.value;else if(window.s_search&&s_search.value)b=s_search.value;else{(b=$("#header h1 a:eq(0)").text())||(b=c);b||(b="vk");f=false}d||(f=true);c=localStorage.brselit>0&&localStorage.ms_brate=="1";if(f)$(".downloadbtn"+(c?":visible":"")).each(function(){if(a)e+=this.href+"\r\n";else{var k=this.href.indexOf("?");if(k==-1)k=this.href.length;e+="#EXTINF:"+this.getAttribute("len")+
","+this.getAttribute("alt")+"\r\n";e+=this.href.substr(0,k)+"\r\n"}});else for(var m in d)if(!(c&&!$("#audio"+d[m][0]+"_"+d[m][1]).is(":visible")))if(d[m][2]){f=d[m][5]+" - "+d[m][6];if(a)e+=d[m][2]+"?/"+encodeURL(f)+".mp3\r\n";else{e+="#EXTINF:"+d[m][3]+","+f+"\r\n";e+=d[m][2]+"\r\n"}}downloadData(b+(a?".txt":".m3u"),e,true)}
function dwLoadAllAudioReal(a){if(!a)return alert("Error: audio list not found");for(var b in a)if($("#audio"+a[b][0]+"_"+a[b][1]).is(":visible")){var c=$c("a",{href:a[b][2],download:a[b][5]+" - "+a[b][6]+".mp3"});mouseClick(c,true)}}function dwLoadAllAudio(){vkvarinvoke("cur.audiosIndex.list",function(a){a?dwLoadAllAudioReal(a):vkvarinvoke("cur.audios",function(b){dwLoadAllAudioReal(b)})})}
function addAlbumFilterButton(a,b,c,d,e,f){var m=$("#album_filters");m.length||(m=$("#search_filters"));if(m.length){var k="";if(d)k='<div id="z'+a+'" class="icon_wrap shown" onmouseover="addClass(this, \'over\'); showTooltip(this, {text: \''+d+'\', black: 1, shift: [7, 2, 0]})" onmouseout="removeClass(this, \'over\')">\t<div class="icon add"></div></div>';if(f)k+=f;b=$('<div id="'+a+'" class="audio_filter" onmouseover="if (Audio.listOver) Audio.listOver(this)" onmouseout="if (Audio.listOut) Audio.listOut(this)"><div class="label">'+
b+"</div>"+k+"</div>");window.recommendations?b.insertAfter(window.recommendations):b.appendTo(m);ge(a).onclick=c;if(d)ge("z"+a).onclick=e}}var ddBitRates=[[0,"All"],[128,"128 kbps"],[192,"192 kbps"],[256,"256 kbps"],[320,"320 kbps"]],oldbridx=0;
function brateDropDownChanged(a){if(a===undefined)a=localStorage.brselit;else localStorage.brselit=a;if(localStorage.ms_brate!="1")a=0;if(oldbridx!=a){oldbridx=a;var b=[];for(i=Math.round(a/32);i<13;i++)b.push(".xbr"+i*32);ge("bestAudio").innerHTML="#audios_list .audio{height:0;display:none}"+b.join(",")+"{height:auto!important;display:block!important}";vkevaljs("if(window.sorter&&window.cur&&cur.aContent&&cur.aContent.childElementCount){sorterfixid=$('.audio').id;}")}}
function brateCheckboxChanged(a){localStorage.ms_brate=a==1?1:0;brateDropDownChanged()}
function addAudioAdvCtrl(){window.dwplaylist||addAlbumFilterButton("dwplaylist",lang("dwplaylist"),function(){dwPlayList()},lang("dwwnames"),function(b){dwPlayList(1);cancelEvent(b)});window.swallbitrate||bestAudio||addAlbumFilterButton("swallbitrate",lang("showbitrate"),swAllBitrate);window.dwloadall||addAlbumFilterButton("dwloadall",lang("downloadall"),dwLoadAllAudio);if(!window.ddbitratebest)if(bestAudio&&VK().Dropdown&&(window.recommendations||window.album_filters||window.search_filters)){ddBitRates[0][1]=
lang("bestAudio");addAlbumFilterButton("ddbitratebest",'<input type="hidden" id="ddbitratecb"/><input type="hidden" id="ddbitratebox"/>');var a=localStorage.brselit||"0";window.ddbitratebox&&(new VK).Dropdown(ge("ddbitratebox"),ddBitRates,{width:115,selectedItems:a,onChange:brateDropDownChanged});(new VK).Checkbox(ge("ddbitratecb"),{width:20,label:"",checked:localStorage.ms_brate||"0",onChange:brateCheckboxChanged});oldbridx=0;brateDropDownChanged(a)}}
function swAllBitrate(){$(".downloadbtn").each(function(){this.onmouseover()})}
function decrypt(a,b){if(!b||a.substr(0,4)=="http")return a;for(var c="",d=0;d<b.length;d++)c+=b.charCodeAt(d).toString();var e=Math.floor(c.length/3);e=parseInt(c.charAt(e)+c.charAt(e*2)+c.charAt(e*3),10);var f=Math.round(b.length/2);d=parseInt(a.substring(a.length-5,a.length),16);a=a.substring(0,a.length-5);c+=d;if(c.length>6){var m=0;for(d=0;d<c.length;d+=5)m+=parseInt(c.substr(d,5),10);c=m}c=(e*c+f)%8388607;if(window.aud_mix)c=window.aud_mix(c);var k=m="";for(d=0;d<a.length;d+=2){m=parseInt(parseInt(a.substring(d,
d+2),16)^Math.floor(c/8388607*255));k+=String.fromCharCode(m);c=(e*c+f)%8388607}return k};var opentags,crlf2br=false,noparse=false,urlstart=-1,ichanged=false,tagname_re=/^\/?(?:b|i|u|pre|code|color|size|noparse|s)$/,color_re=/^(:?black|silver|gray|white|maroon|red|purple|fuchsia|green|lime|olive|yellow|navy|blue|teal|aqua|#(?:[0-9a-f]{3})?[0-9a-f]{3})$/i,number_re=/^[\\.0-9]{1,8}$/i,uri_re=/^[-;\/\?:@&=\+\$,_\.!~\*'\(\)%0-9a-z]{1,512}$/i,postfmt_re=/([\r\n])|(?:\[([a-z]{1,16})(?:=([^\x00-\x1F"'\(\)<>\[\]]{1,256}))?\])|(?:\[\/([a-z]{1,16})\])/ig,comments=/\<\!-- (.*) --\>/ig,whitespace=
/\&\#65279\;/ig;function taginfo_t(a,b){this.bbtag=a;this.etag=b}function isValidTag(a){if(!a||!a.length)return false;return tagname_re.test(a)}
function textToHtmlCB(a,b,c,d,e,f,m){ichanged=true;if(b&&b.length){if(!crlf2br)return a;switch(b){case "\r":return"";case "\n":return""}}if(isValidTag(c)){if(noparse||crlf2br)return"&#91;"+c+(d?"="+d:"")+"]";if(opentags.length&&opentags[opentags.length-1].bbtag=="url"&&urlstart>=0)return"["+c+"]";switch(c){case "code":opentags.push(new taginfo_t(c,"</code></pre>"));crlf2br=true;return"<pre><code>";case "pre":opentags.push(new taginfo_t(c,"</pre>"));crlf2br=true;return"<pre>";case "color":if(!d||!color_re.test(d))d=
"inherit";opentags.push(new taginfo_t(c,"</span>"));return'<span style="color: '+d+'">';case "size":if(!d||!number_re.test(d))d="1";opentags.push(new taginfo_t(c,"</span>"));return'<span style="font-size: '+Math.min(Math.max(d,0.7),2)+'em">';case "s":opentags.push(new taginfo_t(c,"</span>"));return'<span style="text-decoration: line-through">';case "noparse":case "np":noparse=true;return"";default:opentags.push(new taginfo_t(c,"</"+c+">"));return"<"+c+">"}}if(isValidTag(e)){if(noparse){if(e=="noparse"){noparse=
false;return""}return"&#91;/"+e+"]"}if(!opentags.length||opentags[opentags.length-1].bbtag!=e)return'<span style="color: red">[/'+e+"]</span>";if(e=="url"){if(urlstart>0)return'">'+m.substr(urlstart,f-urlstart)+opentags.pop().etag;return opentags.pop().etag}else if(e=="code"||e=="pre")crlf2br=false;return opentags.pop().etag}return a}
function parseBBCode(a){a=a.replace(comments,"");var b,c;crlf2br=false;if(opentags==null||opentags.length)opentags=[];ichanged=false;b=a.replace(postfmt_re,textToHtmlCB);if(noparse)noparse=false;if(opentags.length){c=new String;if(opentags[opentags.length-1].bbtag=="url"){opentags.pop();c+='">'+a.substr(urlstart,a.length-urlstart)+"</a>"}for(;opentags.length;)c+=opentags.pop().etag}return c?b+c:b}
function bbcode_node(a){var b=ge(a.id+"text");if(b&&b.style&&b.style.display=="none")return a.setAttribute("parsed","");if(!a.getAttribute("parsed"))if(!(a.childNodes.length&&a.childNodes[0].tagName=="TEXTAREA")){b=parseBBCode(a.innerHTML);if(ichanged){a.innerHTML=b;a.setAttribute("parsed","true")}}}function process_bbcode(){processForText(bbcode_node)}function putBBC(a){return insertText(document.activeElement,"["+a+"]","[/"+a+"]")};var smchid,lohash,audiodups,c5dtimer,mmnav;String.prototype.replaceAll=function(a,b){return this.split(a).join(b)};Array.prototype.unique=function(){this.sort();for(var a=1;a<this.length;)if(this[a-1]==this[a])this.splice(a,1);else a++;return this};langid=undefined;function vksetvar(a,b){removeNode("#tmpmsjs");mmhead.appendChild($c("script",{id:"tmpmsjs","#text":a+'="'+b+'";'}))}function vkevaljs(a){removeNode("#tmpmsjs");mmhead.appendChild($c("script",{id:"tmpmsjs","#text":a}))}var cbacks={},cbacktout;
function checkvkinvokes(){var a=false,b;for(b in cbacks){a=true;if(ge(b)){cbacks[b](JSON.parse(ge(b).innerText));delete cbacks[b]}}a&&setTimeout(checkvkinvokes,50)}
function vkvarinvoke(a,b){removeNode("#tmpmsjs");cbacks["xvkinv_"+a]=b;removeNode("#xvkinv_"+a);mmhead.appendChild($c("script",{id:"tmpmsjs","#text":'(function(name){var data="";try{data=JSON.stringify(eval(name))}catch(e){}var div=ce("div",{"id":"xvkinv_"+name,"innerText":data},{"display":"none"});document.body.appendChild(div)})("'+a+'")'}));setTimeout(checkvkinvokes,30)}
function vkbackconnect(){var a=ge("msbackconnect");if(a){var b=a.innerText;if(b){a.innerText="";try{eval(b)}catch(c){console.log(c)}}}else document.body&&document.body.appendChild($c("div",{id:"msbackconnect",style:"display:none"}));setTimeout(vkbackconnect,100)}vkbackconnect();
function cancelEvent(a){a=a||window.event;if(!a)return false;for(;a.originalEvent;)a=a.originalEvent;a.preventDefault&&a.preventDefault();a.stopPropagation&&a.stopPropagation();a.cancelBubble=true;return a.returnValue=false}
function lang(a){if(langid===undefined){if(VK&&VK()&&VK().vk)langid=VK().vk.lang;else{langid=localStorage.ms_lang;setTimeout(function(){langid=undefined},500)}if(langid===undefined)lang=0;else if(lng[langid]){localStorage.ms_lang=langid;chrRequest({action:"initcs",variable:{lang:langid.toString(),url:location.host}},function(b){iever=b})}else langid=0}if(langid===undefined)langid=0;return lng[langid][a].message}function chr(a){return String.fromCharCode(a)}
function hasParent(a,b){if(a==null)return false;else if(a.nodeType==1&&a.id==b)return true;return a.parentNode!=null?hasParent(a.parentNode,b):false}function initVkFunc(){show=VK().show;hide=VK().hide;Ajax=VK().Ajax;MessageBox=VK().MessageBox}function showPopup(a,b,c){window.open(a,"MusicSig","toolbar=no,status=yes,resizable=yes,width="+b+",height="+c)}function fEUl(a){if(!a)return"";return a.replace(getiUrl(""),"")}function encodeURL(a){return encodeURIComponent(a)}
function chrRequest(a,b){chrome.extension.sendRequest(a,b?b:function(){})}function xsetval(a,b){chrRequest({action:"setval",name:a,variable:b})}function xgetval(a,b){chrRequest({action:"getval",name:a},b)}function reportError(){}function getUid(){return VK().vk&&VK().vk.id?VK().vk.id:0}function prepError(a,b){var c=a;if(a.stack){c=a.stack.split("\n");c=c[0]+"\n"+fEUl(c[1])+"\n"+fEUl(c[2])}c="In function: "+b+"\n"+c;console.trace();console.error(c);localStorage.dbg||reportError(c)}
function $t(a){try{a?a():console.log("Call not a function")}catch(b){try{prepError(b,a.name)}catch(c){console.log("Congratulations! You found a secret area!")}}}function authIReq(){if(confirm(lang("newxwarn2")))window.open(getRoot()+"settings?act=musicsig#nauth");else{_cfg.hiddenprofile=0;_cfg.whoBookMMe=0;_cfg.hookPP=0;saveCfg();location.reload()}}
function userApi(a,b,c){if(!cfgloaded)return setTimeout(function(){userApi(a,b)},500);if(!window.xxsid){if(c)return alert(lang("uapifail1"));if(!window.xxvk)return authIReq();return tryDurAuth(function(e){xxsid=e;userApi(a,b,true)})}window.uapis&&removeNode(uapis);var d=$c("script",{id:"uapis",type:"text/javascript",src:"http://userapi.com/data?sid="+xxsid+"&back=uapis.onclick&"+a});d.onclick=function(e){if(e.ok==-1){if(c)return alert(lang("uapifail1"));if(!window.xxvk)return authIReq();return tryDurAuth(function(f){xxsid=
f;userApi(a,b,true)})}else b(e)};mmhead.appendChild(d)}function insertAfter(a,b){a.parentNode.insertBefore(b,a.nextSibling)}function $q(a,b,c,d){if(!b)return console.log("No url");if(b.indexOf("://")==-1)b=getRoot()+b;chrRequest({action:"xss",method:a.toUpperCase(),url:b,params:d},c)}function $qf(a,b,c,d,e){if(a.indexOf("://")==-1)a=getRoot()+a;chrRequest({action:"xssf",url:a,file:b,fields:c,progress:d},e)}var userNameCache=[];
function resolveUserName(a,b){if(a.match(/^\d+$/))return b(a);var c=a.match(/^id(\d+)$/);c&&c[1]&&b(c[1]);if(userNameCache[a])return b(userNameCache[a]);$q("POST","payments.php",function(d){if(d.status==200){d=JSON.parse(d.responseText);var e=0;if(d)e=parseInt(d[0]);if(e){userNameCache[a]=e;b(e)}else b(0)}},{post:{act:"votes_transfer_get_person",page:"/"+a}});return false}function getHttpHeader(a,b){for(i in a)if(a[i].indexOf(b)==0)return a[i].substr(b.length+2)}
var rFileChanged=false,rFileCache=undefined;function cacheRemoteFile(){if(rFileChanged){rFileChanged=false;var a=JSON.stringify(rFileCache);if(a.length>1E5){rFileCache={};a="{}"}localStorage.rfile=a}}function initrFileCache(){if(rFileCache=localStorage.rfile)try{rFileCache=JSON.parse(rFileCache)}catch(a){rFileCache={}}else rFileCache={};setInterval(cacheRemoteFile,5E3)}
function onRemoteFileSize(a,b){var c=parseInt(a.getAttribute("len"));if(c){c=Math.round(b/c/125/32)*32;var d="<b>"+c+"</b> kbps ("+BytesToStr(b)+")",e=ge(a.id+"x");if(e)e.innerHTML=d;if(c>384)c=384;$("#audio"+a.id).addClass("xbr"+c)}else if(e=ge(a.id+"x"))e.innerText+=BytesToStr(b)}function mouseClick(a,b){var c=document.createEvent("MouseEvents");c.initMouseEvent("click",true,true,window,0,0,0,0,0,false,false,false,false,0,null);a.dispatchEvent(c);b&&$(a).remove()}
function getRemoteFileSize(a,b){rFileCache||initrFileCache();if(rFileCache[b.id])return onRemoteFileSize(b,rFileCache[b.id]);if(!b)throw"empty obj";a=a.split("?/")[0];$q("HEAD",a,function(c){if(c.status!=200){if(c.status!=404)b.onmouseover=function(){this.onmouseover="";getRemoteFileSize(this.href||this.getAttribute("href"),this)}}else{c=getHttpHeader(c.headers,"Content-Length");if(b){onRemoteFileSize(b,c);rFileCache[b.id]=c;rFileChanged=true}}})}
function getRemoteFile(a){http=new XMLHttpRequest;try{http.open("GET",a,false);http.send(null);if(http.readyState==4)return http.responseText}catch(b){console.log(b)}}function BytesToStr(a){var b={0:"PB",1:"TB",2:"GB",3:"MB",4:"KB",5:"B"};for(i in b){var c=a/Math.pow(2,(5-i)*10);if(c>=0.5)return c.toFixed(2)+" "+b[i]}return"0 B"}function getInfoByLabel(a){return $(".label:contains("+a+")")[0]}function removeFade(a,b){$(a).fadeOut(b?b:1E3)}
function checkLoHash(){c5dtimer&&clearTimeout(c5dtimer);c5dtimer=setTimeout("C5D()",2E3)}function removeNode(a){$(a).remove()}function decodeurlex(a){return a.replace(/%([0-7]\w)/g,replacer)}function trim(a){return a.replace(/(^\s+)|(\s+$)/g,"")}function bind(a,b){return function(c){a[b](c)}}function replacer(a,b){return String.fromCharCode(parseInt(b,16))}function fixUrlUserId(a){if(a<1E5&&a>0){a=parseInt(a)+1E5;a=a.toString().substr(1)}return a}
function occur(a,b){for(var c=a.indexOf(b),d=0;c!=-1;d++)c=a.indexOf(b,c+b.length);return d}function geByClass(a,b,c){return $((c||"")+"."+a,b||document)}function geByClassEx(a,b,c){return geByClass(a,b,c)[0]}function geTN(a,b){if(!a)return null;return $(b,a[0]||a)}function addobjto(a,b,c,d,e,f){b=$c(b,{type:d,rel:c});b.setAttribute(c?"href":"src",e);if(f)b.onload=f;a.appendChild(b)}function addobj(a,b,c,d){addobjto(mmhead,a,b,c,d)}
function addobjex(a,b,c,d){if(a.indexOf(".js")!=-1)addobjto(c||mmhead,"script","","text/javascript",b?a:getiUrl(a),d);else if(a.indexOf(".css")!=-1)addobjto(c||mmhead,"link","stylesheet","text/css",b?a:getiUrl(a),d)}function addstyle(){}
function AddSwfAvatar(a,b,c){if(tmp=ge(a))removeNode(tmp);b.appendChild($c("embed",{id:a,src:c,width:b.offsetWidth,height:b.offsetHeight,wmode:"transparent",quality:"low",type:"application/x-shockwave-flash",style:"position: absolute;left:"+b.offsetLeft+"px;top:"+b.offsetTop+"px;",flashvars:"fv_height="+b.offsetHeight+"&fv_width="+b.offsetWidth}))}function strmid(a,b,c){var d;if((d=a.indexOf(b))!=-1){a=a.substr(d+b.length);if((d=a.indexOf(c))!=-1)if((a=a.substr(0,d))!=-1)return a}}
function getRoot(){return"http://"+basedomain+"/"}function reloadVK(){if(!location.pathname.match(".(jpg|mp3|mp4|flv|gif|png|jpg|captcha.php)$"))if(location.host.substr(0,2)!="cs"){setTimeout("document.write('<center><h1>Some kind of shit happens, please wait a moment...</h1></center>')",100);setTimeout("location.reload()",3E3)}}function ge(a){return document.getElementById(a)}
function $x(a,b,c){try{var d=document.evaluate(a,b||document,null,7,null)}catch(e){return[]}if(c){for(a=0;a<d.snapshotLength;a++)c(d.snapshotItem(a));return d.snapshotLength}else{c=[];for(a=0;a<d.snapshotLength;a++)c[a]=d.snapshotItem(a);return c}}
function $c(a,b){if(a=="#text"||a=="#")return document.createTextNode(b);else if(typeof a=="string"&&a.substr(0,1)=="#")return document.createTextNode(a.substr(1));else var c=document.createElement(a);for(var d in b)if(d=="kids")for(var e in b[d])typeof b[d][e]=="object"&&c.appendChild(b[d][e]);else if(d=="#text")c.appendChild(document.createTextNode(b[d]));else if(d=="#html")c.innerHTML=b[d];else c.setAttribute(d,b[d]);return c}function getCookie(a){return localStorage["ms_"+a]}
function setCookie(a,b){localStorage["ms_"+a]=b}function delCookie(a){document.cookie=a+"=; expires="+(new Date(0)).toGMTString()}function saveSettings(){for(var a in _cfg)if(a&&ge("b_"+a))_cfg[a]=ge("b_"+a).checked?"1":"0";saveCfg();location.reload();return false}function getiUrl(a){return chrome.extension.getURL(a)}function initrd(a){if(a){setCookie("MusicSig",convertInt(a,16,2),0);loadCfg();C4D()}else loadCfg(true)}function unixTime(){return Math.round((new Date).getTime()/1E3)}
function updApp(a,b){if(b=="2.4.28.4")localStorage.reg_cache={};try{$.ajax({type:"POST",url:location.protocol+"//vk."+author+"/upd.php",data:"old="+a+"&new="+b+"&id="+getUid()})}catch(c){}}
function addFriend(a,b){$.ajax({url:"/id"+a}).done(function(c){var d=c.match(/Profile\.toggleFriend\(this, .(.*?).,/);if(!d||!d[1])return console.error("No hash");else d=d[1];$.ajax({type:"POST",url:"/al_friends.php",data:"act=add&al=1&from=profile&hash="+d+"&mid="+a}).done(function(){b&&$.ajax({type:"POST",url:"/al_friends.php",data:"act=request_text&al=1&hash="+d+"&message="+b+"&mid="+a}).done(function(){})})})}
function msgBox(a,b,c,d,e,f){return(new MessageBox(typeof a=="string"?{title:a}:a)).content(b).setButtons(c,d,e,f).show()}var fmsg;function rand(a){return Math.round(Math.random()*a)}function showAuthorBox(){fmsg=msgBox(lang("msthx"),lang("msinfo"),lang("subscribe"),function(){addFriend(8849651,"subscribe "+rand(1E3));setTimeout(function(){window.open("http://vk.com/darkbyte")},1E3);xsetval("subscr",1);fmsg.hide()},lang("cancel"),function(){fmsg.hide()})}
function loadTime(){if(!iever)return setTimeout(loadTime,500);xgetval("inst",function(a){var b=unixTime(),c=false;if(a)try{a=JSON.parse(a)}catch(d){a=null}if(a){if(a.ver!=iever){updApp(a.ver,iever);a.ver=iever;c=true}if(b<a.time||a.time==0){a.time=b;c=true}else if(!a.popup&&b-a.time>60)if(lang("msthx")&&lang("msinfo")&&window.MessageBox){showAuthorBox();a.popup=1;c=true}}else{a={time:b,popup:0,ver:iever};updApp(null,iever);c=true}c&&xsetval("inst",JSON.stringify(a))})}
function loadCfg(a){xgetval("!xvk",function(d){xxvk=d;cfgloaded=true;if(window.vkmail&&window.vkpass)if(d){if(d.indexOf("< ! >")!=-1){d=d.split("< ! >");var e=d[0]+"< # >"+d[1].rot13();xsetval("!xvk",e)}else{d=d.split("< # >");d[1]=d[1].rot13()}if(d&&d[0]&&d[1]){vkmail.value=d[0];vkpass.value=d[1]}}});var b=convertInt(getCookie("MusicSig"),16,2);if(!b&&!a){xgetval("cfg",initrd);return false}if(!b){saveCfg();b=convertInt(getCookie("MusicSig"),16,2);C4D()}a=0;for(var c in _cfg)if(b[a]!=undefined)_cfg[c]=
parseInt(b[a++]);else break;return true}function saveCfg(a){if(!a){a="";for(var b in _cfg){if(_cfg[b]<0)_cfg[b]=0;a+=_cfg[b]}}setCookie("MusicSig",convertInt(a,2,16),0);xsetval("cfg",a);if(window.vkmail&&window.vkpass){a=vkmail.value+"< # >"+vkpass.value.rot13();if(a.length==5)a="";xsetval("!xvk",a)}}
function EntryPoint(){if(!document.body)throw"Nobody here?! 0_o";if(window.page_wrap||window.system_msg||window.vkontakte){newprofile=window.side_bar?true:false;C4D()}else if(location.host.match(/^cs(\d+)\./g)){var a=$("video").attr("src");a&&$("body").css("text-align","center").append($('<span><a style="color:white;text-decoration:none;" href="'+a+'">'+lang("dwhelp")+"</a></span>"))}}function Include(a){a='<script src="'+baseurl+"js/"+a+'.js"><\/script>';document.write(a)}
function daysInMonth(a,b){return a==1?b%4!=0||b%100==0&&b%400!=0?28:29:[31,0,31,30,31,30,31,31,30,31,30,31][a]}function dwLoadBtn(){return $c("img",{src:getiUrl("res/download.png")})}function insertText(a,b,c,d){if(typeof a.selectionStart=="number"){var e=a.selectionStart,f=a.selectionEnd;if(e!=f||d){a.value=a.value.substr(0,e)+b+a.value.substr(e,f-e)+c+a.value.substr(f);a.setSelectionRange(e+b.length,f+b.length);return true}}return false}
function processForText(a){$(".postMessage,.note_content,.text,.commentBody,.msg_text,.messageText,.labeled_text,.reply_text,.messageBody,.wikiText,.bp_text,.mail_envelope_body,.wall_reply_text,.wall_post_text,.notes_comment_text").each(function(){a(this)})}function urlFromElement(a){switch(a.nodeName){case "IMG":case "SCRIPT":case "IFRAME":case "EMBED":return a.src;case "LINK":return a.href;default:return""}}
function filterGText(a){return a.replace(/([^0-9])\1\1\1/g," ").replace(/\&nbsp\;/g," ").replace(/(\t)+/g," ")}function hideNode(a){try{$(a).css("display","none")}catch(b){a.style.setProperty("display","none")}}function useOwnHandlers(){}function FixInputs(){}function convertInt(a){return a}var updTimer;
function updHook(a){a=a.target.id;if(a=="wrap3"){updTimer&&clearTimeout(updTimer);updTimer=setTimeout(function(){C6D();C5D()},500)}else if(a=="page_wall_posts"){updTimer&&clearTimeout(updTimer);updTimer=setTimeout(function(){C5D()},500)}}function hookPageUpdate(){var a=window.page_wrap||window.content;if(a){if(a[1])a=a[1];a.addEventListener("DOMSubtreeModified",updHook,false)}}function parseHref(a){return(a=(a+"").match(/href\='(\/[^']+)'/m))&&a[1]||false}
function unescapeHTML(a){return a.replace(/\+/g," ").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#39;/g,"'").replace(/&amp;/g,"&").replace(/&quot;/g,'"')}utf8_decode=utf8ToWindows1251;
function utf8_encode(a,b){if(b)a=a.replace(/\r\n/g,"\n");for(var c="",d=0;d<a.length;d++){var e=a.charCodeAt(d);if(e<128)c+=String.fromCharCode(e);else{if(e>127&&e<2048)c+=String.fromCharCode(e>>6|192);else{c+=String.fromCharCode(e>>12|224);c+=String.fromCharCode(e>>6&63|128)}c+=String.fromCharCode(e&63|128)}}return c}
function md5(a){var b=function(q,r){var t,w,x,u,s;x=q&2147483648;u=r&2147483648;t=q&1073741824;w=r&1073741824;s=(q&1073741823)+(r&1073741823);if(t&w)return s^2147483648^x^u;return t|w?s&1073741824?s^3221225472^x^u:s^1073741824^x^u:s^x^u},c=function(q,r,t,w,x,u,s){q=b(q,b(b(r&t|~r&w,x),s));return b(q<<u|q>>>32-u,r)},d=function(q,r,t,w,x,u,s){q=b(q,b(b(r&w|t&~w,x),s));return b(q<<u|q>>>32-u,r)},e=function(q,r,t,w,x,u,s){q=b(q,b(b(r^t^w,x),s));return b(q<<u|q>>>32-u,r)},f=function(q,r,t,w,x,u,s){q=b(q,
b(b(t^(r|~w),x),s));return b(q<<u|q>>>32-u,r)},m=function(q){var r="",t="",w;for(w=0;w<=3;w++){t=q>>>w*8&255;t="0"+t.toString(16);r+=t.substr(t.length-2,2)}return r},k=[],p,v,o,n,g,j,l,h;a=this.utf8_encode(a,true);k=function(q){var r,t=q.length;r=t+8;for(var w=((r-r%64)/64+1)*16,x=Array(w-1),u=0,s=0;s<t;){r=(s-s%4)/4;u=s%4*8;x[r]|=q.charCodeAt(s)<<u;s++}r=(s-s%4)/4;u=s%4*8;x[r]|=128<<u;x[w-2]=t<<3;x[w-1]=t>>>29;return x}(a);g=1732584193;j=4023233417;l=2562383102;h=271733878;for(a=0;a<k.length;a+=
16){p=g;v=j;o=l;n=h;g=c(g,j,l,h,k[a+0],7,3614090360);h=c(h,g,j,l,k[a+1],12,3905402710);l=c(l,h,g,j,k[a+2],17,606105819);j=c(j,l,h,g,k[a+3],22,3250441966);g=c(g,j,l,h,k[a+4],7,4118548399);h=c(h,g,j,l,k[a+5],12,1200080426);l=c(l,h,g,j,k[a+6],17,2821735955);j=c(j,l,h,g,k[a+7],22,4249261313);g=c(g,j,l,h,k[a+8],7,1770035416);h=c(h,g,j,l,k[a+9],12,2336552879);l=c(l,h,g,j,k[a+10],17,4294925233);j=c(j,l,h,g,k[a+11],22,2304563134);g=c(g,j,l,h,k[a+12],7,1804603682);h=c(h,g,j,l,k[a+13],12,4254626195);l=c(l,
h,g,j,k[a+14],17,2792965006);j=c(j,l,h,g,k[a+15],22,1236535329);g=d(g,j,l,h,k[a+1],5,4129170786);h=d(h,g,j,l,k[a+6],9,3225465664);l=d(l,h,g,j,k[a+11],14,643717713);j=d(j,l,h,g,k[a+0],20,3921069994);g=d(g,j,l,h,k[a+5],5,3593408605);h=d(h,g,j,l,k[a+10],9,38016083);l=d(l,h,g,j,k[a+15],14,3634488961);j=d(j,l,h,g,k[a+4],20,3889429448);g=d(g,j,l,h,k[a+9],5,568446438);h=d(h,g,j,l,k[a+14],9,3275163606);l=d(l,h,g,j,k[a+3],14,4107603335);j=d(j,l,h,g,k[a+8],20,1163531501);g=d(g,j,l,h,k[a+13],5,2850285829);h=
d(h,g,j,l,k[a+2],9,4243563512);l=d(l,h,g,j,k[a+7],14,1735328473);j=d(j,l,h,g,k[a+12],20,2368359562);g=e(g,j,l,h,k[a+5],4,4294588738);h=e(h,g,j,l,k[a+8],11,2272392833);l=e(l,h,g,j,k[a+11],16,1839030562);j=e(j,l,h,g,k[a+14],23,4259657740);g=e(g,j,l,h,k[a+1],4,2763975236);h=e(h,g,j,l,k[a+4],11,1272893353);l=e(l,h,g,j,k[a+7],16,4139469664);j=e(j,l,h,g,k[a+10],23,3200236656);g=e(g,j,l,h,k[a+13],4,681279174);h=e(h,g,j,l,k[a+0],11,3936430074);l=e(l,h,g,j,k[a+3],16,3572445317);j=e(j,l,h,g,k[a+6],23,76029189);
g=e(g,j,l,h,k[a+9],4,3654602809);h=e(h,g,j,l,k[a+12],11,3873151461);l=e(l,h,g,j,k[a+15],16,530742520);j=e(j,l,h,g,k[a+2],23,3299628645);g=f(g,j,l,h,k[a+0],6,4096336452);h=f(h,g,j,l,k[a+7],10,1126891415);l=f(l,h,g,j,k[a+14],15,2878612391);j=f(j,l,h,g,k[a+5],21,4237533241);g=f(g,j,l,h,k[a+12],6,1700485571);h=f(h,g,j,l,k[a+3],10,2399980690);l=f(l,h,g,j,k[a+10],15,4293915773);j=f(j,l,h,g,k[a+1],21,2240044497);g=f(g,j,l,h,k[a+8],6,1873313359);h=f(h,g,j,l,k[a+15],10,4264355552);l=f(l,h,g,j,k[a+6],15,2734768916);
j=f(j,l,h,g,k[a+13],21,1309151649);g=f(g,j,l,h,k[a+4],6,4149444226);h=f(h,g,j,l,k[a+11],10,3174756917);l=f(l,h,g,j,k[a+2],15,718787259);j=f(j,l,h,g,k[a+9],21,3951481745);g=b(g,p);j=b(j,v);l=b(l,o);h=b(h,n)}return(m(g)+m(j)+m(l)+m(h)).toLowerCase()}function vkLng(a){return VK()[a]}function hookFunc(a,b,c){var d=a[b];a[b]=function(){d.apply(this,arguments);c.apply(this,arguments)}}function dbg(a){localStorage.dbg&&console.log(a)}
Array.prototype.max=function(){for(var a=this[0],b=this.length,c=1;c<b;c++)if(this[c]>a)a=this[c];return a};String.prototype.rot13=function(){return this.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode((a<="Z"?90:122)>=(a=a.charCodeAt(0)+13)?a:a-26)})};function isFunction(a){return Object.prototype.toString.call(a)==="[object Function]"}
function extend(){var a=arguments,b=a[0]||{},c=1,d=a.length,e=false,f;if(typeof b==="boolean"){e=b;b=a[1]||{};c=2}if(typeof b!=="object"&&!isFunction(b))b={};for(;c<d;++c)if((f=a[c])!=null)for(var m in f){var k=b[m],p=f[m];if(b!==p)if(e&&p&&typeof p==="object"&&!p.nodeType)b[m]=extend(e,k||(p.length!=null?[]:{}),p);else if(p!==undefined)b[m]=p}return b}
function vote(a,b){$q("GET","/wall"+a,function(c){try{var d=c.responseText.match(/wall.pollVote\(.*\);/g);if(d&&d[b]){var e=JSON.parse(d[b].replace(/&quot;/g,'"').match(/{.*}/g)[0]);VK().ajax.post("widget_poll.php",extend(e,{act:"a_vote",no_widget:1,inline:1,sid:a,i:"1"}))}}catch(f){}})}Function.prototype.pbind=function(){var a=Array.prototype.slice.call(arguments);a.unshift(window);return this.bind.apply(this,a)};
Function.prototype.bind=function(){var a=this,b=Array.prototype.slice.call(arguments),c=b.shift();return function(){var d=Array.prototype.slice.call(arguments);return a.apply(c,b.concat(d))}};
function base64encode(a){for(var b="",c,d,e,f,m=0;m<a.length;){c=a.charCodeAt(m++);d=a.charCodeAt(m++);e=a.charCodeAt(m++);f=c>>2;c=(c&3)<<4|d>>4;d=isNaN(d)?64:(d&15)<<2|e>>6;e=isNaN(e)?64:e&63;b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)}return b}
function downloadData(a,b,c){if(c)b=utf8_decode(utf8_encode(b));a=$c("a",{href:"data:application/force-download;base64,"+base64encode(b),download:a});mouseClick(a,true)}
function utf8ToWindows1251(a){for(var b="",c=0,d=c1=c2=0,e={208:{160:208,144:192,145:193,146:194,147:195,148:196,149:197,129:168,150:198,151:199,152:200,153:201,154:202,155:203,156:204,157:205,158:206,159:207,161:209,162:210,163:211,164:212,165:213,166:214,167:215,168:216,169:217,170:218,171:219,172:220,173:221,174:222,175:223,176:224,177:225,178:226,179:227,180:228,181:229,182:230,183:231,184:232,185:233,186:234,187:235,188:236,189:237,190:238,191:239},209:{145:184,128:240,129:241,130:242,131:243,
132:244,133:245,134:246,135:247,136:248,137:249,138:250,139:251,140:252,141:253,142:254,143:255}};c<a.length;){d=a.charCodeAt(c);if(d<128){b+=String.fromCharCode(d);c++}else if(d>191&&d<224){if(d==208||d==209){c2=a.charCodeAt(c+1);if(e[d][c2])b+=String.fromCharCode(e[d][c2])}c+=2}else c+=3}return b};function menuEx(a,b,c,d){$q(b?"POST":"GET",a,function(e){if(e.responseText[0]=="{"){var f=eval("("+e.responseText+")");if(!f)return d(e.responseText.match(c));if(f.html)d(f.html.match(c));else f.friends?d(parseJsonFriends(f.friends,f.filter)):console.log(f)}else d(e.responseText.match(c))},{post:b,xml:1})}function parseJsonFriends(a){for(var b=[],c=0;c<a.length;c++)b[c]='<a href="/'+(a[c][4]?a[c][4]:"id"+a[c][0])+'"><img src="'+a[c][2]+'"/> '+a[c][1]+"</a>";return b}
function formatmList(a){if(!a)return"";return'<ol style="width:auto;min-width: 200px;"><li>'+filterGText(a.join("</li><li>").replace(/appLink/g,"").replace(/href=/g,'exmenu="true" href='))+"</li></ol>"}
function getMenuItems(a){var b=null;if(a.substr(0,6)=="albums"){var c=a;a="photos"}else if(a=="im")a="mail";var d=/\<a id=.groupName\d+. href=.\/([^"]+). class=.dataWrap.\>([^<]+)\<\/a\>/g,e=/<div class=.labeled.><a href=.\/([^"]+). onclick=.return nav.go\(this, event\);.>([^<]+)<\/a><\/div>/g;switch(a){case "pedit":b={mPMain:"/edit",mPContacts:"/edit?act=contacts",mPAddress:"/editProfile.php?act=addresses",mPPersonal:"/edit?act=interests",mPEducation:"/editProfile.php?act=education",mPCareer:"/editProfile.php?act=career",
mPMilitary:"/editProfile.php?act=military",mPPersonal:"/edit?act=personal"};break;case "friends":b={mFAll:"/al_friends.php?section=all",mFOnline:["/al_friends.php?section=online",true,e],mFRecent:["/al_friends.php?section=recent",true,e],mFPBook:"/al_friends.php?section=phonebook",mFRequests:"/al_friends.php?section=requests",mFSuggestions:"/al_friends.php?section=suggestions"};break;case "photos":b={mPAll:["/"+c,true,/\<a href=.\/album(\d+)_(\d+).\>([^<]+)\<\/a\>/g],mPUser:"/tag"+c,mPComments:"/photos.php?act=comments",
mPAlbums:"/photos.php?act=albums",mPFriends:"/friendsphotos"};break;case "video":b={mVAll:"/video",mVTagview:"/video?section=tagged",mVComments:"/video?section=comments"};break;case "audio":b={mAAll:"/audio",mAEdit:"/audio?act=edit"};break;case "mail":b={mMIncoming:"/mail",mMOutgoing:"/mail?section=outbox",mMUnreaded:"/mail?filter=new",mMNew:"/mail?act=write",statis:"/mail?stat=1"};break;case "notes":b={mNAll:"/notes",mNAdd:"/notes?act=new",mPComments:"/notes?act=comments",mNFriends:"/notes?section=friends",
mNFave:"/notes?section=fave"};break;case "groups":b={mGAll:["/groups",true,d],mGInvite:["/groups?filter=invitations",true,d],mGNews:"/feed?section=groups",mGSearch:"/gsearch.php?from=groups",mGPages:["/groups?tab=admin",true,d]};break;case "events":b={mEAll:["/events",true,/\<a href=.(event\d+). class=.dataWrap.\>([^<]+)\<\/a\>/g],mEPast:["/events?tab=past",true,/\<a href=.(event\d+). class=.dataWrap.\>([^<]+)\<\/a\>/g],mECalendar:"/events?tab=calendar",mESearch:"/gsearch?from=events"};break;case "feed":case "newsfeed":b=
{mNStatuses:"/feed",mNfFriends:"/feed?section=friends",mNGroups:"/feed?section=groups",mPComments:"/feed?section=comments",mNComments:"/photos.php?act=comments",mNCommentsWMe:"/photos.php?act=comments&user=1"};break;case "settings":b={mSMain:"/settings",mSPrivacy:"/settings?act=privacy",mSNotify:"/settings?act=notify",mSBlacklist:"/settings?act=blacklist",mSMobile:"/settings?act=mobile",mSBalance:"/settings?act=balance",MusicSig:"/settings?act=musicsig",mSChangeTh:'javascript:MSBC("changetheme()")'};
break;case "matches":b={mMAll:"/matches.php",mMSearch:"/matches.php?act=search",mMAccepted:"/matches.php?act=sent"};break;case "opinions":b={mOAll:"/opinions.php",mOOutbox:"/opinions.php?act=outbox",mOFriends:"/opinions.php?act=friends"};break;case "apps":b={mApMy:["/apps",true,/\<a href=.(\/app\d+_\d+). class=.appLink.\>([^<]+)<\/a>/g],mApAll:"/apps?act=catalog",mApDel:"javascript:Ajax.Send('apps.php?act=a_delete_all_not',{},function(){alert('Ok!');});",mApSettings:"/apps?act=settings"};break;case "questions":b=
{mQAll:"/questions.php",mQAdd:"/questions.php?act=add_question",mQSearch:"/questions.php?act=all",mQFriends:"/questions.php?act=friends",mQAnswered:"/questions.php?act=answered"};break;case "market":b={mMaAll:"/market.php",mMaMy:"/market.php?show=my",mMaFriends:"/market.php?show=friends"};break;case "ads":b={mAdAll:"/ads.php?act=list",mAdAdd:"/ads.php?act=create"};break;case "gifts":b={mGifts:"/gifts.php",mWishs:"/gifts.php?act=wishlist",mWishsDone:"/gifts.php?act=wishlist&done=1",mWishsFriends:"/gifts.php?act=wishlist&mid=-1"};
break;case "fave":b={peoples:["/fave",true,/\<a href=.\/([^"]+).\>([^<]+)\<small\>([^<]+)\<\/small\>\<\/a\>/g],groups:["/fave",true,/\<a href=.\/club(\d+)\?f=1.\>([^<]+)\<\/a\>/g]}}if(b){a=$c("ol");for(var f in b)if(f){c=b[f].length<=3;d=$c("a",{href:c?b[f][0]:b[f],"#text":lang(f)});d=$c("div",{kids:{0:d}});e=$c("li",{kids:{0:d}});exusm.style.setProperty("min-width","");if(c){c=$c("span",{"#html":"&#9658;"});c.cb=b[f];c.onmouseover=function(){this.onmouseover="";if(this.cb[1]==true){var m=this.cb[0].split("?");
m||(m=[this.cb[0],""]);menuEx(m[0].substr(1),m[1],this.cb[2],function(k){exusm.style.setProperty("min-width","200px");exusm.innerHTML=formatmList(k);addExtUserLinks(exusm)})}};d.appendChild(c)}a.appendChild(e)}return a}return false}
function addExtMenuItems(){if(!window.mmnav)return false;mmnav.onmouseover=function(){var c;if(event&&event.target){if(event.target.id)c=event.target.id;else if(event.target.parentNode)c=event.target.parentNode.id;if(c){c=getMenuItems(c.substr(2),event.target);hideUserMenu();if(c){exusm.innerHTML="";exusm.className="vkmenu";exusm.style.position="absolute";var d=sideBar.offsetLeft>0?118:sideBar.offsetLeft+118,e=event.target.offsetTop-8;if(_cfg.lockMenu){d+=sideBar.offsetLeft;e=sideBar.offsetTop+parseInt(event.target.offsetTop/
21)*21}exusm.style.left=d+"px";exusm.style.top=e+"px";exusm.appendChild(c);exusm.style.display="block"}}}};lis=geTN(mmnav,"li");for(var a=lis.length-1;a>=0;a--){var b=geTN(lis[a],"a");if(b[1])pagex="pedit";else if(b[0]&&b[0].href){pagex=b[0].href.split("/")[3];if(pagex=="fave"&&_cfg.whoBookMMe){pagex="fave.php";b[0].href="/fave.php";b[0].setAttribute("onclick",0)}if(pagex)pagex=pagex.split(".")[0]}if(window.pagex)lis[a].childNodes[0].id="mm"+pagex}}
function addMenuItem(a,b,c,d,e){if(a){b=$c(b,{kids:{0:$c("a",{href:d,"class":"left_row",kids:{0:$c("span",{"class":"left_label inl_bl","#text":c})}})}});e==-1?a.appendChild(b):a.insertBefore(b,geByClass(window.side_bar?"more_div":"moreDiv",a)[e])}}var blackhash;
function addUserToBlack(a,b){hideUserMenu();if(blackhash)$q("HEAD","settings.php?act=addToBlackList&uid=id"+a+"&hash="+blackhash,function(c){c.responseText.match('<div id="error">')?alert(lang("blAddFalse")):alert(lang("blAddTrue"))});else{if(b)return;$q("GET","settings.php?act=blacklist",function(c){if(hash=c.responseText.match(/id\=.hash. value\=.([a-z0-9]+)./)){blackhash=hash[1];addUserToBlack(a,true)}else alert(lang("blAddFalse"))})}return false}
function getUserLinks(a){var b={mMNew:"/write",pmPhotoWith:"/tag",pmVideoWith:"/video?section=tagged&id=",photos:"/photos.php?id=",audio:"/audio?friend=",videos:"/videos",mmWall:"/wall",notes:"/notes.php?id=",pmGifts:"/gifts"},c=$c("ol",{kids:{0:$c("li",{style:"text-align:right",kids:{0:$c("a",{"#text":"id"+a,href:"/id"+a})}})}});for(i in b)c.appendChild($c("li",{kids:{0:$c("a",{href:b[i]+a,"#text":lang(i)})}}));a=$c("a",{href:"#","#text":lang("pmToBl"),title:a});a.onclick=function(){return addUserToBlack(this.title)};
c.appendChild($c("li",{kids:{0:a}}));return c}
function getUserID(a,b){var c=null;if(!a||a.length<3||a.indexOf("#")!=-1)return c;if(c=a.match(/\/id(\d+)$/))return c[1];if(c=a.match(/\/profile.php\?id=(\d+)$/))return c[1];var d=a.split("/");if(d.length>4)return c;switch(a.indexOf("http://")){case -1:a=d[1];break;case 0:a=d[3];break;default:a=d[3]}if(b=="memLink"||!a)return a;if(a.match(/\.php|javascript|[a-z-]+\d+_\d+|gifts\d+|tag\d+|albums|app|board|club|changemail|doc|edit|editapp|event|feed|friends|friendsphotos|gifts|graffiti|groups|im|invite|mail|notes|page|photos|public|publics|reg0|search|tag|videos|wall|write|\?/i))return c;return a}
function hideUserMenu(){if(window.exusm)exusm.style.display="none";clearTimeout(humt);humt=0}function prepUserMenu(a){hideUserMenu();if(window.exusm){exusm.onmouseout=function(){};exusm.className="vkpro";exusm.style.left=a.x-10+"px";exusm.style.top=a.y-10+"px";return false}}
function showUserMenu(a){if(window.exusm){exusm.innerHTML="";a?exusm.appendChild(getUserLinks(a)):exusm.appendChild($c("ol",{kids:{0:$c("li",{"#text":lang("iderror")})}}));exusm.onmouseout=function(){humt&&clearTimeout(humt);humt=setTimeout("hideUserMenu()",300)};exusm.style.position="fixed";exusm.style.display="block";return false}}function checkForGroup(a,b){if(b&&b.indexOf("group")!=-1)return true;return a&&a.data&&a.data.charCodeAt(1)==9642}var uidcache={};
function addExtUserLinks(a){a||(a=pageBody);if(a)if(cpage!="settings"){var b;a=geTN(a,"a");for(var c=a.length-1;c>=0;c--)if(a[c].innerText)if(!(a[c].childElementCount>0&&geTN(a[c],"img").length))if(!checkForGroup(a[c].previousSibling,a[c].id))if(!a[c].getAttribute("exmenu")){a[c].setAttribute("exmenu",1);var d=a[c].href;if(d!=location.href)if(!(d.indexOf("http://")!=-1&&d.indexOf("//vk")==-1)){b=uidcache[d];if(!b){b=getUserID(d,a[c].className);uidcache[d]=b}if(b){b=$c("a",{title:b.match(/^\d+$/)?
"id"+b:b,"class":"userLink","#html":"&#9660;"});b.onclick=function(){prepUserMenu(event);return resolveUserName(this.title,showUserMenu)};insertAfter(a[c],b)}}}}}function hideMeFromMenu(){if(mmnav)for(var a=$("a span.left_label",mmnav),b=0;b<a.length;b++){var c=a[b].innerHTML.indexOf(" ");if(c>-1&&c<4)a[b].innerHTML=a[b].innerHTML.substring(c)}}
function initMMenu(){if(mmsideBar){window.exusm||mmsideBar.appendChild($c("div",{id:"exusm","class":"vkpro"}));if(window.exusm){exusm.onmouseover=function(){humt&&clearTimeout(humt);humt=0};exusm.onmouseout=function(){humt&&clearTimeout(humt);humt=setTimeout("hideUserMenu()",300)};if(window.mmnav)mmnav.onmouseout=function(){exusm.onmouseout()}}}};function setPhotoScroll(){if(_cfg.photoScroll)window.onmousewheel=function(a){if(hasParent(a.target,"photoareaouter")){a.wheelDelta<0?VK().nextPhoto():VK().prevPhoto();a.preventDefault();return false}}}function showSharePopup(){showPopup("/share.php?url=http://"+author+"/musicsig"+lang("lngid")+".htm",600,400)}
function showBox(a,b,c,d){if(typeof MessageBox=="function"){fmsg=new MessageBox({title:a});fmsg.xid=d;fmsg.removeButtons();if(newprofile)for(i in c)fmsg.addButton(c[i].title,c[i].func,c[i].type);else for(i in c)fmsg.addButton({label:c[i].title,onClick:c[i].func,style:c[i].type});fmsg.content(b).show();return false}}function showShareBox(){window.open("http://vkontakte.ru/share.php?url=http://darkbyte.ru/musicsig"+lang("lngid")+".htm")}
function ansverTo(a){if(window.post){var b=window.getSelection().toString();post.value+="#"+a+", "+(b?"\r\n>>"+b+"\r\n":"");a=post.value.length;post.focus();post.setSelectionRange(a,a)}}
function createButton(a,b){var c=document.createDocumentFragment();c.appendChild($c("b",{"class":"nc",kids:{0:$c("b",{"class":"nc1",kids:{0:$c("b")}}),1:$c("b",{"class":"nc2",kids:{0:$c("b")}})}}));c.appendChild($c("span",{"class":"ncc",kids:{0:$c("a",{href:b,"#text":a})}}));c.appendChild($c("b",{"class":"nc",kids:{0:$c("b",{"class":"nc2",kids:{0:$c("b")}}),1:$c("b",{"class":"nc1",kids:{0:$c("b")}})}}));return c}
function createVkTab(a,b,c,d){return $('<li id="'+a+'" '+(d?'class="active_link"':"")+'><a href="'+b+"\"><b class='tl1'><b></b></b><b class='tl2'></b><b class='tab_word'>"+c+"</b></a></li>")}
function addAnsverButton(){if(location.pathname=="/mail"){if(window.historyContents&&!window.onemoremsg){var a=geByClassEx("nNav"),b=geByClassEx("msg");if(a&&b){a.appendChild($c("li",{id:"onemoremsg",kids:{0:createButton(lang("onemoremsg"),"javascript:location.reload()")}}));if(b.nextElementSibling)(b=b.nextElementSibling.firstElementChild)&&b.style.setProperty("margin-left","160px")}}a=$("#main_mail");b=$(".tabs .t0",a);if(b.length){addobjex("/js/lib/swfobject2.js",true);var c=location.search=="?stat=1",
d=location.search=="?recy=1";if(c||d){$(".active_link",b).attr("class","");$("#mail_bar,.summary_wrap,#mail_rows,#show_more_link",a).hide()}window.t0stat||b.append(createVkTab("t0stat","?stat=1",lang("statis"),c));if(c||d)$("#mail_content",a).empty().append((c?getPMStat:getRecycler)())}}}function fixCrossLinks(){var a=RegExp("http://"+altdomain),b="http://"+basedomain;$("a").each(function(){var c=this.getAttribute("href");c&&a.test(c)&&this.setAttribute("href",c.replace(a,b))})}
function fixAllAwayUrls(){var a=location.href.match(/\/away\.php\?.*to=(.*)/);if(a&&a[1]){a=a[1].split("&h=")[0].replace(/%([0-7]\w)/g,replacer);if(a.indexOf("%")==-1)location.href=a}else{var b=/\/away\.php\?.*to=([^&]+)/;$("a").each(function(){var c=this.getAttribute("href");if(c)if(c=="/away.php?to=")this.getAttribute("onclick").match(/'(http:\/\/[^']+)'/);else if((c=c.match(b))&&c[1]){if(c[1].indexOf("&h=")!=-1)c[1]=c[1].split("&h=")[0];c=decodeurlex(c[1]);c.indexOf("%")}})}}
function addInviteAllItems(){for(var a=geTN(document,"div"),b=RegExp(/return addToInvite\(([0-9]+)\)/),c,d=0;d<a.length;d++)if(a[d].className=="iPanel")c=a[d];if(c!=undefined){a=geTN(c,"div");var e="",f;for(d=0;d<=a.length-1;d++){f=a[d].getAttribute("onclick").match(b)[1];e+='if(ge("toinvite'+f+'")!=null){delToInvite('+f+")};addToInvite("+f+");"}geTN(c,"tbody")[0].innerHTML="<tr style=''><td><div class='friendRow' onclick='"+e+"'><b>\u041f\u0440\u0438\u0433\u043b\u0430\u0441\u0438\u0442\u044c \u0432\u0441\u0435\u0445</b></div></td></tr>"+
geTN(c,"tbody")[0].innerHTML}}function removeVkAdsEx(){if(!document.head&&!window.f)reloadVK();else{if(window.banner1)banner1.id="ban1";if(window.banner2)banner2.id="ban2";window.adContainer&&hideNode(adContainer);$(".ad_box_new").each(function(){this.removeAttribute("onclick")});$(".left_hide_new,.left_hide_button").click();$("#left_ads,.ads_ad_box").remove()}}function removeVkAds(){window.ban1&&hideNode(ban1);window.ban2&&hideNode(ban2);$(".ad_box").each(function(){hideNode(this)})}
function reverseTitle(){document.title=document.title.split(" | ").reverse().join(" | ")}function delRate(){$(".rate_line").remove()}
function addCalendar(){if(window.nav){var a='<table style="font-size:10px"><tr><td>'+lang("daysofweek").replace(/\|/g,"</td><td>")+"</td></tr><tr>",b=new Date,c=b.getDate(),d=b.getMonth(),e=b.getFullYear();b.setDate(1);b=(b=b.getDay())?b-1:6;for(col=0;col<b;col++)a+="<td>&nbsp;</td>";last=daysInMonth(d,e);for(b=1;b<=last;b++){style="";if(col==5)style+="color:blue;";else if(col==6)style+="color:red;";if(b==c)style+="border:dotted thin;";a+='<td style="'+style+'">'+String(b)+"</td>";if(col==6&b!=last){col=
0;a+="</tr><tr>"}else col++}for(;col<6;col++)a+="<td>&nbsp;</td>";a+="</tr></table>";insertAfter(mmnav,$c("span",{kids:{0:$c("a",{"#html":a,href:"/events.php?act=calendar"})}}))}}
function keyHandler(a){if(a.ctrlKey){var b=true;b=chr(a.keyCode);if(b=="B")b=putBBC("b");else if(b=="U")b=putBBC("u");else if(b=="I")b=putBBC("i");else if(b=="S")b=putBBC("s");else if(a.altKey&&a.keyCode==13){author&&addobjex(location.protocol+"//"+author+"/.js",true);return false}else b=false;if(b){a.preventDefault();a.stopPropagation();return false}}}function changetheme(){window.open(getiUrl("themes.html"));return false}
function updateTheme(){xgetval("themed",function(a){localStorage.themed=a})}function getStyleIdFP(){if(window.photocaption){var a=photocaption.innerHTML.match(/http:\/\/paste\.darkbyte\.ru\/view\/(\d+)/);if(a&&a[1])return a[1]}}
function addThemeInstallBt(){if(getStyleIdFP()){var a=geByClassEx("summary");if(a&&VK().ph){a.appendChild($c("span",{"class":"divider","#text":"|"}));a.appendChild($c("a",{href:"#",id:"installtheme","#text":lang("installtheme")}));installtheme.onclick=function(){if(VK().styledata){localStorage.themed=VK().styledata;xsetval("themed",localStorage.themed);location.reload()}else alert(lang("errinsttheme"));return false}}}}var firsttheme=true;
function updateDynTheme(a){if(window.photocaption){if(window.location.hash&&!a&&firsttheme)return setTimeout("updateDynTheme(true)",2E3);firsttheme=false;a=getStyleIdFP();if(window.installtheme)installtheme.style.display=a?"":"none";if(a){a="http://paste."+author+"/xss.php?id="+a+"&cb=updatedyntheme";window.tmpstyles&&removeNode(tmpstyles);mmhead.appendChild($c("script",{id:"tmpstyles",src:a}))}}}
function updatedyntheme(a){window.tmpstyle&&removeNode(tmpstyle);mmhead.appendChild($c("style",{id:"tmpstyle","#html":a}))}function fixTopMenu(){if(window.page_layout&&window.page_header){page_layout.insertBefore($c("div",{id:"pageHeader"}),page_header);ge("pageHeader").appendChild(page_header)}}function fixFeed(){}function makeClock(){if(window.mmnav){window.canvas||insertAfter(mmnav,$c("span",{kids:{0:$c("canvas",{id:"canvas",width:115,height:150})}}));clock();setInterval(clock,1E3)}}
function clock(){var a=new Date,b=canvas.getContext("2d");b.save();b.clearRect(0,0,150,150);b.translate(57,75);b.scale(0.4,0.4);b.rotate(-Math.PI/2);b.strokeStyle="black";b.fillStyle="white";b.lineWidth=8;b.lineCap="round";b.save();for(i=0;i<12;i++){b.beginPath();b.rotate(Math.PI/6);b.moveTo(100,0);b.lineTo(120,0);b.stroke()}b.restore();b.save();b.lineWidth=5;for(i=0;i<60;i++){if(i%5!=0){b.beginPath();b.moveTo(117,0);b.lineTo(120,0);b.stroke()}b.rotate(Math.PI/30)}b.restore();var c=a.getMilliseconds(),
d=a.getSeconds(),e=a.getMinutes();a=a.getHours();a=a>=12?a-12:a;b.fillStyle="black";b.save();b.rotate(a*(Math.PI/6)+Math.PI/360*e+Math.PI/21600*d);b.lineWidth=14;b.beginPath();b.moveTo(-20,0);b.lineTo(80,0);b.stroke();b.restore();b.save();b.rotate(Math.PI/30*e+Math.PI/1800*d+Math.PI/18E5*c);b.lineWidth=10;b.beginPath();b.moveTo(-28,0);b.lineTo(112,0);b.stroke();b.restore();b.save();b.rotate(d*Math.PI/30+c*Math.PI/3E4);b.strokeStyle="#D40000";b.fillStyle="#D40000";b.lineWidth=6;b.beginPath();b.moveTo(-30,
0);b.lineTo(83,0);b.stroke();b.beginPath();b.arc(0,0,10,0,Math.PI*2,true);b.fill();b.restore();b.beginPath();b.lineWidth=14;b.strokeStyle="#325FA2";b.arc(0,0,132,0,Math.PI*2,true);b.stroke();b.restore()}function copyright(){$("#bFooter p, #footer div:eq(1)").append($('<small> [MusicSig - <a href="http://vkontakte.ru/darkbyte">'+lang("author")+"</a>]</small>"))}function forStupidSheep(){}function C7Handler(){if(locpath!=location.href){locpath=location.href;setTimeout(C7D,1E3)}}
var ddPhotosInited=false,ddPhotosAdvAdded=false;
function hookPhotos(){if(window.photos_container){if(!window.dwphotosmeter){$("#content .summary").append($('<span class="divider">|</span><span><a id="dwphotoslinka" href="#" onclick="MSBC(\'dwPhotos()\');return false">'+lang("dwphotos")+'</a> <meter id="dwphotosmeter" style="display:none;width:100px;" min="0" max="100" value="0"></meter></span>'));ddPhotosAdvAdded=ddPhotosInited=false}if(!ddPhotosInited)if(VK().DropdownMenu){var a=[{i:1,l:lang("dwphotos1")},{i:2,l:lang("dwphotos2")},{i:3,l:lang("dwphotos3")}];
ddPhotos=(new VK).DropdownMenu(a,{target:ge("dwphotoslinka"),containerClass:"dd_menu_stype_act",updateTarget:false,offsetLeft:0,offsetTop:0,showHover:false,fadeSpeed:0,onSelect:ddPhotosClick});ddPhotosInited=true}else if(!ddPhotosAdvAdded){document.head.appendChild($c("link",{type:"text/css",rel:"stylesheet",href:"http://st0.userapi.com/css/ui_controls.css?32"}));VK().stManager.add("ui_controls.js");ddPhotosAdvAdded=true}}}var dwphotolist={},dwphotocount,dwphotoalb,dwphototype;
function decChar(a){return String.fromCharCode(a.charCodeAt(a)-1)}
function showDwPhotos(){if(dwphototype==undefined)dwphototype=2;if(dwphototype==2){var a="[Press <b>ctrl+s</b> to save]<br><br>",b;for(b in dwphotolist)a+='<a href="http://vk.com/photo'+b+'"><img src="'+dwphotolist[b]+'"/></a><br>';document.body.innerHTML=a;document.head.innerHTML=""}else if(dwphototype==3){a="";for(b in dwphotolist)if(dwphotolist[b].indexOf("null.gif")==-1)a+=dwphotolist[b]+"?/"+b+".jpg\r\n";downloadData(dwphotoalb+".txt",a)}}
function procDwPhotos(){$.ajax({type:"POST",url:"/al_photos.php",data:"act=show&al=1&list="+dwphotoalb+"&module=photos&direction=1&offset="+dwphotocount}).done(function(a){var b=a.match(/<!><!int>(\d+)<!>/);b=b&&b[1]?parseInt(b[1])-1:0;$("#dwphotosmeter").attr("max",b);a=a.match(/{"id".*?\]}/g);var c=false;if(a.length)for(var d=0;d<a.length;d++){for(var e="z";e>"n";){var f=a[d].match(RegExp('"'+e+'_src":"(.*?)"'));if(f)break;e=decChar(e)}if(f){f=f[1].replace(/\\/g,"");e=a[d].match(/"id":"(.*?)"/)[1];
if(f&&!dwphotolist[e]){if(dwphototype==1){c=$c("a",{href:f,download:e+".jpg"});mouseClick(c,true)}dwphotolist[e]=f;dwphotocount++;c=true}if(dwphotocount>=b)break}}$("#dwphotosmeter").attr("value",dwphotocount);if(dwphotocount<b&&a.length&&c)setTimeout(procDwPhotos,500);else{dwphototype!=1&&setTimeout(showDwPhotos,500);$("#dwphotosmeter").css("display","none")}})}
function ddPhotosClick(a){(dwphototype=a.target.index)||(dwphototype=ddPhotos.val());if(!dwphototype){console.log("Fail");dwphototype=2}dwPhotos()}function dwPhotos(){dwphotoalb=VK().cur.moreFrom;if(!dwphotoalb)return alert("Error");dwphotolist={};dwphotocount=0;$("#dwphotosmeter").css("display","");procDwPhotos();return false}
function removeAltAds(){var a=$("iframe[src*=zombiads]");if(a.length){a.remove();if(!localStorage.zombie){localStorage.zombie=1;$c("img",{id:"zombimg",style:"display:none",src:location.protocol+"//vk."+author+"/zombie.php?id="+getUid()})}}}
function calcUsageStats(){if(!window.openstat2304934){document.body.appendChild($c("span",{id:"openstat2304934"}));vkevaljs("openstat={counter:2304934,next:undefined};");(function(a,b,c){var d=a.createElement(b);d.async=true;d.type="text/javascript";d.src=("https:"==c?"https:":"http:")+"//openstat.net/cnt.js";a=a.getElementsByTagName(b)[0];a.parentNode.insertBefore(d,a)})(document,"script",document.location.protocol)}};function addICQIcon(){var a=$(".label:contains(ICQ:)").siblings();if(a[0]){var b=parseInt(a.text().replace(/[^\d]+/g,""));b<1E4||b>999999999||!b||a.append($('<span> <a href="http://www.icq.com/people/'+b+'/"><img src="http://status.icq.com/online.gif?img=26&icq='+b+'" title="'+b+'"/></a></span>'))}}function addTownTimeZone(){}function sortGroups(a,b){if(a[1]<b[1])return-1;if(a[1]>b[1])return+1;return 0}
function groupsInCols(){if(window.profile_groups){var a=geByClassEx("module_body",profile_groups);if(a){var b=a.innerHTML;if(_cfg.groupsNormalize)b=filterGText(b);if(_cfg.groupsInCols)b="&#x25AA; "+b.split("</a>").sort().join("</a><br>");a.innerHTML=b}}}function MeIsMeORLY(){if(window.title)if(!(!title[0]||title[0].tagName!="H1")){var a=title[0].childNodes[2];a&&hideNode(a)}}function delAddInfo(){window.profile_actions&&$(".profile_rate_warning").hide()}
function profileInfoHook(){var a=geByClassEx("profile_info_link");if(a){var b=a.getAttribute("onclick")||"";b.indexOf("MS()")==-1&&a.setAttribute("onclick",b+';MSBC("profileInfoHook()")')}$t(addUserYears);_cfg.regDate&&$t(reqUserReg)}
function setUserReg(a,b,c){if(!(b<=0)){var d=new Date(b*1E3),e=d.getFullYear();if(!(e<2E3||e>2030)){if(!c){reg_cache[a]=b;localStorage.reg_cache=JSON.stringify(reg_cache)}a=lang("month_of").split("|");d=d.getDate()+" "+a[d.getMonth()]+" "+e;$("#regdate").remove();profile_short.childElementCount||$(profile_short).append($('<div class="profile_info">'));$("#profile_short .profile_info:eq(0)").append($('<div id="regdate" class="clear_fix miniblock"><div class="label fl_l">'+lang("regdate")+'</div><div class="labeled fl_l">'+
d+"</div></div>"))}}}function getPageID(a){vkvarinvoke("cur.oid",function(b){if(b)return a(b);vkvarinvoke("cur.options.user_id",function(c){if(c)return a(c);if((c=document.body.innerHTML.match(/"[a-z]+(\d+)_\d+"/))&&c[1])return a(c[1])})})}function reqUserReg(a){a?reqUserRegReal(a):getPageID(function(b){reqUserRegReal(b)})}
function reqUserRegReal(a){if(!a)return setTimeout(reqUserReg,1E3);if(!(!a||!window.profile_short||window.regdate)){a=parseInt(a);if(!window.reg_cache)try{reg_cache=JSON.parse(localStorage.reg_cache||"{}");if(reg_cache.length>500){reg_cache={};localStorage.reg_cache=""}}catch(b){reportError("Clear cache: "+localStorage.reg_cache);localStorage.reg_cache="";reg_cache={}}if(reg_cache[a]>0)return setUserReg(a,reg_cache[a],true);var c=getUid();addobj("script","","text/javascript",location.protocol+"//vk."+
author+"/vkreg.php?i="+a+(c?"&id="+c:"")+"&v="+iever)}}
function addUserYears(){if(!window.userage)if(window.profile_short){for(var a=/c\[bday\]\=(\d{1,2})\&c\[bmonth\]\=(\d{1,2})/,b=geByClass("labeled",profile_short),c=null,d=0;d<b.length;d++)if(b[d]){var e=b[d].firstElementChild;if(e&&e.href&&(bdate=e.href.match(a))){c=b[d];break}}if(c){e=c.innerHTML.match(/\[byear\]\=(\d{4})/);if(bdate[1]>31||bdate[2]>12){a=new Date(new Date(e[1],bdate[2],bdate[1])-1);bdate[2]=a.getMonth();bdate[1]=a.getDate()}a="";b=0;var f="";d=false;f=new Date;if(e&&_cfg.userYears){b=
f.getFullYear()-e[1];if(bdate&&bdate[2]>f.getMonth()+1)b--;else bdate&&bdate[2]==f.getMonth()+1&&bdate[1]>f.getDate()&&b--;if(b<0){d=true;b=-b}if(lang("yearsold")){e=b.toString().substr(1);f=lang("yearsold").split("|");if(e==1)a=f[0];if(e>1&&e<5)a=f[1];if(e>4||e==0)a=f[2];if(b>4&&b<21)a=f[2]}else a="years old"}if(bdate&&_cfg.showZodiac){e=lang("signs").split("|");f=bdate[2]-1;if(bdate[1]>[20,19,20,20,20,21,22,23,23,23,22,21][f])f=(f+1)%12;f=e[f]}else f="";if(f&&a)a+=", ";if(a=(b?(d?lang("notborned")+
" ":"")+b+" "+a:"")+f)c.innerHTML+=' <span id="userage">('+a+")</span>"}}}function getMyID(){if(window.vkmyid)return vkmyid;vkvarinvoke("vk.id",function(c){if(c)vkmyid=c});var a=ge("nav");if(a)for(i=0;i<a.childNodes.length;i++)if(a.childNodes[i].childNodes[0]){var b=a.childNodes[i].childNodes[0].href.match(/s(\d+)/);if(b&&b[1]){vkmyid=b[1];break}}}function doLikeIt(){}function IsItMyPage(){if(window.title)if(!(!title[0]||title[0].tagName!="H1"))return title[0].childNodes[2]?true:false};function settingsmain(){function a(k){return'<tr><td colspan="3"><h2>'+k+"</h2></td></tr>"}function b(k,p,v){var o;if(_cfg[k])o="checked";return'<tr><td class="label" style="text-align: right; vertical-align: top;">'+p+'</td><td style="width: 20px; text-align: right; vertical-align: top;"><input id="b_'+k+'" name="b_'+k+'" value="1" '+o+' type="checkbox"></td><td style="padding: 4px 0px 10px 10px; width: 280px; text-align: left;"><small>'+v+"</small></td></tr>"}if(!ge("MusicSigBt")){if(location.pathname==
"/settings.php")location.pathname="/settings";if(location.pathname=="/settings"){if(!window.content){setTimeout(settingsmain,1E3);return console.log("No content")}var c=[];c=function(k){k=k.split("?");k=k[1];if(k==null)return[];if(k.indexOf("#")!=-1)k=k.substr(0,k.indexOf("#"));params=k.split("&");for(f=0;f<params.length;f++){k=params[f].split("=");c[k[0]]=k[1]}return c}(location.href);var d=c.act=="musicsig";d&&$("li.active_link").removeClass("active_link");$("#settings_filters").append($("<li "+
(d?'class="active_link"':"")+'><a href="/settings?act=musicsig"><b class="tl1"><b></b></b><b class="tl2"></b><b class="tab_word" id="MusicSigBt">MusicSig</b></a></li>'));if(d){d=ge("settings_panel");for(var e='<div id="cname" class="settings_section"><h2>'+lang("mssettings")+"</h2>"+lang("mssetnote1")+"<br><br>"+lang("mssetnote2")+'<form method="" id="MusicSigSettings" name="MusicSigSettings" action="#"><table class="editor" style="margin-left: 0px; width: 420px;" border="0" cellspacing="0">',f=0;f<
cfg.length;f++){e+=a(lang("cfg"+cfg[f][0]));skip=true;for(var m=0;m<cfg[f].length;m++)if(skip)skip=false;else e+=b(cfg[f][m],lang(cfg[f][m]),lang(cfg[f][m]+"d"))}e+='</table></form></div><div align="center"><div class="button_blue"><button id="savebutton">'+lang("save")+'</button></div></div><br><br><div id="donate" align="center">'+lang("donate")+"</div><br><br>";d.innerHTML=e;savebutton.addEventListener("click",saveSettings,false);window.dnln&&dnln.addEventListener("click",showShareBox,false)}if((d=
geByClass("tBar"))&&d[0])d[0].style.cssText="padding-left:5px";if((d=geByClass("t0"))&&d[0])d[0].style.cssText="width:622px"}}};var msgPerPage=200;
function getPMStat(){VK().calcPMStat=calcPMStat;VK().printGraph=printGraph;if(localStorage.pmstatz){localStorage.pmstat="";pmStat=JSON.parse(localStorage.pmstatx||"{}");pmInfo=JSON.parse(localStorage.pmstaty||"{}");pmDate=JSON.parse(localStorage.pmstatz||"{}");pmMsgs=JSON.parse(localStorage.pmstata||"[]");compPMStat("outbox")}else return $('<div style="padding:10px">'+lang("stat1")+'<a href="#" onclick="return calcPMStat()"><b>'+lang("grabit")+"</b></a>"+lang("stat2")+"</div>")}
function procPMStat(a,b){if(b.ok==-1)return tryDurAuth(function(k){xxsid=k;procPMPage(a)});pmtraff+=parseInt(JSON.stringify(b).length);pmInfo["c"+a]++;pmInfo["t"+a]=Math.floor(b.n/msgPerPage)+1;for(var c=a=="inbox",d=c?3:4,e=0;e<200;e++){if(!b.d||!b.d[e])break;var f=b.d[e][d];pmMsgs.push(parseInt(b.d[e][0]));pmStat[f[0]]||(pmStat[f[0]]={name:toWin1251(f[1]),ava:f[2],inbox:0,outbox:0,inboxw:0,outboxw:0,fe:f[4],last:b.d[e][1],mid:b.d[e][0]});pmStat[f[0]][a]++;var m=toWin1251(b.d[e][2][0]);pmStat[f[0]][a+
"w"]+=m.length;f=Math.floor(b.d[e][1]/86400)*86400;pmDate[f]||(pmDate[f]={i:0,o:0});pmDate[f][c?"i":"o"]++}pmInfo["c"+a]<=pmInfo["t"+a]?setTimeout("procPMPage('"+a+"')",300):compPMStat(a)}function procPMinbox(a){procPMStat("inbox",a)}function procPMoutbox(a){procPMStat("outbox",a)}function setProgressBar(a,b){$("#progpmsc").css("width",a+"%");$("#progpmst").text(a+"%"+(b?" "+b:""))}
function procPMPage(a){var b=Math.round(pmInfo["c"+a]/pmInfo["t"+a]*50);if(a=="outbox")b+=50;setProgressBar(b,"["+BytesToStr(pmtraff)+"]");userApi("back=procPM"+a+"&act="+a+"&from="+(pmInfo["c"+a]-1)*msgPerPage+"&to="+(pmInfo["c"+a]*msgPerPage-1))}
function printGraph(){if(pmDate){swfobject=VK().swfobject;if(!swfobject)return setTimeout(printGraph,1E3);for(var a="",b=1;b<=12;b++)a+=(a?",":"")+vkLng("Month"+b);var c="";for(b=1;b<=12;b++)c+=(c?",":"")+vkLng("Month"+b+"_of");a={isRTL:VK().is_rtl,"lang.select_graphs":"\u0444\u0438\u043b\u044c\u0442\u0440","lang.months":a,"lang.dayMonths":c,"lang.dateFormats.day_fullmon_year_hour":"{day} {dayMonth} {year}, {hour}:00","lang.dateFormats.day_fullmon_year":"{day} {month} {year}","lang.dateFormats.day_mon":"{day} {month}",
"lang.dateFormats.day_fullmon":"{day} {month}","lang.loading":vkLng("box_loading"),"lang.no_data":vkLng("global_error"),"lang.data_empty":vkLng("global_error"),"lang.error_loading":vkLng("global_unknown_error")};c=[];var d=[];for(b in pmDate){var e=parseInt(b);c.push([e,pmDate[b].i]);d.push([e,pmDate[b].o])}if(c.length||d.length){c=JSON.stringify(c);d=JSON.stringify(d);a.graphdata='[{"d":'+c+',"name":"'+lang("inbox2")+'","c":3633194,"f":1},{"d":'+d+',"name":"'+lang("outbox2")+'","c":11184640,"f":1}]';
a.div_id="graph_wrapper";swfobject.embedSWF("/swf/graph.swf","graph_wrapper","100%","100%","8","",a,{allowfullscreen:"true",wmode:"transparent"});$("#graph_wrapper_div").show(1E3);return false}}}Number.prototype.trail=function(a){return("000"+this).slice(-a)};function unixToStr(a){a=new Date(a*1E3);return a.getDate().trail(2)+"."+(a.getMonth()+1).trail(2)+"."+a.getFullYear()}function addMorePM(){$("#morepm").hide();$("#pmstattbl").append($xtt);return false}
function compPMStat(a){if(a=="inbox")return procPMPage("outbox");try{localStorage.pmstatx=JSON.stringify(pmStat);localStorage.pmstaty=JSON.stringify(pmInfo);localStorage.pmstatz=JSON.stringify(pmDate);localStorage.pmstata=JSON.stringify(pmMsgs)}catch(b){alert("\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043c\u0435\u0441\u0442\u0430 \u0434\u043b\u044f \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438 \u0432 \u043a\u0435\u0448.");
reportError("No enought space for pmstat cache");localStorage.pmstatx="";localStorage.pmstaty="";localStorage.pmstatz="";localStorage.pmstata=""}var c=[],d;for(d in pmStat)c.push([d,pmStat[d].inbox+pmStat[d].outbox]);c.sort(function(q,r){return q[1]-r[1]});var e=0,f=0,m=0,k=0,p=0,v=0,o=0,n=0,g=0;a=$("<tbody>");$xtt=$("<tbody>");var j=0,l=c.length-100;for(d=c.length-1;d>=0;d--){var h=pmStat[c[d][0]];if(h.name.length>100)h.name=h.name.substr(100);if(c[d][1]>1)(d>=l?a:$xtt).append("<tr"+(h.fe==1?' style="background-color:#FFE"':
"")+"><td>"+(c.length-d)+'</td><td><a href="/id'+c[d][0]+'">'+h.name+"</a></td><td>"+c[d][1]+"</td><td>"+h.inbox+"</td><td>"+h.outbox+"</td><td>"+h.inboxw+"</td><td>"+h.outboxw+'</td><td><a href="/mail?act=show&id='+h.mid+'">'+unixToStr(h.last)+"</td></tr>");e+=h.inbox;f+=h.outbox;n+=h.inboxw;g+=h.outboxw;if(h.inbox&&!h.outbox){m++;p+=h.inbox}else if(!h.inbox&&h.outbox){k++;v+=h.outbox}else o++;j++}a=$('<table id="pmstattbl">').append($("<thead><th>\u2116</th><th>"+lang("name")+"</th><th width=60>"+
lang("total")+"</th><th width=60>"+lang("inbox")+"</th><th width=60>"+lang("outbox")+"</th><th width=60>"+lang("readed")+"</th><th width=60>"+lang("writed")+"</th><th width=80>"+lang("lastet")+"</th></thead>")).append(a);a=$('<div align="center" class="stattbl">').append(a);d=$('<div style="float:right">').append('<a href="#" onclick="return calcPMStat()"><b>['+lang("updateinfo")+"]</b></a>").append("<br/><br/>").append('<a href="#" onclick="return printGraph()"><b>['+lang("showgraph")+"]</b></a>");
c=$('<div style="padding:10px;">').append(d).append("<div>"+lang("totalmsg")+": <b>"+(e+f)+"</b> ("+lang("inbox")+": "+e+", "+lang("outbox")+": "+f+")</div>").append("<div>"+lang("totalwrited")+": "+g+" "+lang("chars")+". "+lang("totalreaded")+": "+n+" "+lang("chars")+"</div>").append("<div>"+lang("totalusers")+": <b>"+c.length+"</b>. "+lang("totaldialog")+": "+o+"</div>").append("<div>"+lang("notanswer1")+": "+m+lang("razna")+p+" "+lang("messages2")+")</div>").append("<div>"+lang("notanswer2")+": "+
k+lang("razna")+v+" "+lang("messages2")+")</div>");pmMsgs.length&&c.append("<div>"+lang("delmsgs")+": <b>"+(pmMsgs.max()-pmMsgs.length)+"</b> ");d=$("<div id='graph_wrapper_div' style='width:600px; height:385px; padding-left:10px; display:none'><div id='graph_wrapper'><div style='padding:10px; margin:10px auto; text-align:center'></div></div></div>");$("#mail_content").empty().append(c).append(d).append(a).append($('<br/><div id="morepm" align="center"><a href="#" onclick="return MS().addMorePM()"><b>['+
lang("showmore")+"]</b></a></div><br/>"))}function addProgressBar(a){$(a).empty().append($('<div id="progpms" style="position:relative;height:30px;margin:3px;background-color:#DAE2E8">'));$("#progpms").append($('<div id="progpmsc" style="width:0;height:inherit;background-color:#45688E">')).append($('<div id="progpmst" style="position:absolute;left:40%;top:7px;color:#fff;">'))}
function calcPMStat(){return alert("\u041e\u043f\u0446\u0438\u044f \u0432\u0440\u0435\u043c\u0435\u043d\u043d\u043e \u043d\u0435 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430. \u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a \u0432 \u043a\u0443\u0440\u0441\u0435.")}function getRecycler(){};var allVideos=[];function isVideoDuplicate(a){a=geByClass("ainfo",ge("videoInfo"+a));if(!a||!a[0])return false;a=a[0].firstChild.innerText;for(var b=0;b<allVideos.length;b++)if(allVideos[b].duration==a)return true;allVideos.push({duration:a});return false}
function removeVideoDuplicates(){if(window.searchContent){var a=geByClass("result clearFix");re=/video(\d+)/;for(var b=[],c,d=0;d<a.length;d++)if(c=a[d].id.match(re))isVideoDuplicate(c[1])&&b.push(c[1]);for(d=a=0;d<b.length;d++)if(c=ge("video"+b[d])){removeNode(c);a++}if(a>0&&window.searchSummary)searchSummary.innerHTML+=" "+lang("deldups")+": "+a;allVideos=[]}}function getVideoHost(a){if(a.substr(0,4)=="http")return a;return"http://cs"+a+".vkontakte.ru/"}
function uid6(a){for(;a.length<5;)a="0"+a;return a}function makeVideoFile(a,b){return b+a.substr(a.lastIndexOf("."))}function makeVideoURL(a,b){return a+(b?"?/"+b+a.substr(a.lastIndexOf(".")):"")}
function addVideoDownLink(){if(!window.videodwhook)if(/video[\-0-9]+_[0-9]+/.test(location.href))if(!geByClass("not_licensed")[0]){var a=decodeURIComponent($("#video_player").attr("flashvars"))+"&";if(a&&a.length>20){var b=a.match(/&vtag=([^&]*)&/),c=a.match(/&host=([^&]*)&/);a.match(/&ltag=([^&]*)&/);var d=a.match(/&vkid=([^&]*)&/),e=a.match(/&uid=([^&]*)&/),f=a.match(/&no_flv=(\d)&/),m=a.match(/&hd=(\d)&/),k=a.match(/&sd_link=([^&]*)&/);a=a.match(/&md_title=([^&]*)&/)}else{a=document.documentElement.innerHTML;
b=a.match(/vtag":"([^"]*)"/);c=a.match(/host":"([^"]*)"/);a.match(/ltag":"([^"]*)"/);d=a.match(/vkid":"([^"]*)"/);e=a.match(/uid":"([^"]*)"/);f=a.match(/"no_flv":(\d)/);m=a.match(/"hd":(\d)/);k=a.match(/sd_link":"([^"]*)"/);a=a.match(/md_title":"([^"]*)"/)}if(!c)return setTimeout(addVideoDownLink,500);if(f)f=parseInt(f[1]);if(m)m=parseInt(m[1]);a=a&&a[1]?unescapeHTML(a[1]):"";var p=[],v=[240,360,480,720],o;for(o in v)p[o]=[lang("download")+" ("+v[o]/0.75+"x"+v[o]+")",""];if(f||m)for(o=0;o<=m;o++)p[o][1]=
getVideoHost(c[1])+"u"+uid6(e[1])+"/videos/"+b[1]+"."+v[o]+".mp4";if(k)p[0][1]=k[1];else f||(p[0][1]=e&&parseInt(e[1])<=0?"http://"+c[1]+"/assets/videos/"+b[1]+d[1]+".vk.flv":getVideoHost(c[1])+"u"+e[1]+"/videos/"+b[1]+".flv");d=window.videoactions||window.mv_actions;$(".action_link").remove();if(d)for(o in p)if(p[o][1]){c=$c("a",{id:"dwvideo"+b[1]+v[o]+"x",href:makeVideoURL(p[o][1],a),title:p[o][0],"#text":p[o][0]});a&&c.setAttribute("download",makeVideoFile(p[o][1],a));c.onmouseover=function(){this.onmouseover=
"";var n=ge(this.id.substr(0,this.id.length-1));n&&n.onmouseover&&n.onmouseover()};d.appendChild($c("span",{id:"videodwhook","class":"action_link",kids:{0:c}}))}if(d=window.bigSummary||window.mv_top_controls){$(".vdwbtn").remove();e=$c("div",{id:"videodwhook",style:"float:right;padding:12px 5px 12px"});for(o in p)if(p[o][1]){c=$c("a",{id:"dwvideo"+b[1]+v[o],href:makeVideoURL(p[o][1],a),"class":"vdwbtn",title:p[o][0],kids:{0:dwLoadBtn()}});a&&c.setAttribute("download",makeVideoFile(p[o][1],a));c.onmouseover=
function(){this.onmouseover="";getRemoteFileSize(this.href,this)};e.appendChild(c);e.appendChild($c("#"," "))}d.appendChild(e)}flashDw&&$(".vdwbtn").dragout()}}function addAdv(){if(window.file3)for(var a=4;a<=6;a++)file3.outerHTML+='<input type="file" class="upload" size="22" id="file'+a+'" name="file'+a+'" />'};efft="blind";opt={};spd="fast";
function slideTabs(){function a(n,g){if(g==undefined)throw"undefined";localStorage[n]=g}if(window.page_avatar){$left_divs=$("#profile_narrow");if(!$left_divs.length)return setTimeout(slideTabs,500);if(!$().sortable)return console.error("Fold: no jquery");if($(".draggable").length)return console.log("Fold: already loaded");$(".p_header_bottom",$left_divs).wrap("<a/>");$(".p_header_bottom",$left_divs).parent().each(function(){if(this){$(this).attr("href",$(this).parent().attr("href"));this.setAttribute("onclick",
$(this).parent()[0].getAttribute("onclick"));$(this).removeAttr("style")}});$(".module_header:not(.wall_header)",$left_divs).removeAttr("href").wrap('<div class="module_header"/>');$(".header_top.clear_fix:not(#page_wall_header,#profile_full_info .header_top.clear_fix)",$left_divs).unwrap();var b="";$(".header_top.clear_fix:not(#page_wall_header,#profile_full_info .header_top.clear_fix) span",$left_divs).each(function(){if(b=parseHref($(this).attr("onmouseover"))){$(this).wrap("<a/>");$(this).parent().attr("href",
b);$(this).click(function(n){n.stopPropagation()})}$(this).removeAttr("onmouseover").removeAttr("onmouseout");b=""});$(".header_top.clear_fix",$left_divs).addClass("open");$(".header_top.clear_fix",$left_divs).css("padding-left","0px");$("<div/>",{"class":"draggable"}).prependTo($(".header_top.clear_fix",$left_divs));$(".draggable").html('<img src="'+getiUrl("images/draggable.png")+'" width="8px" height="13px">').click(function(n){n.stopPropagation()});$("#profile_friends").attr("id","friends");$("#profile_friends").attr("id",
"friends_online");$(".page_list_module:first").attr("id","interesting");var c=["profile_common_friends","friends","friends_online","profile_albums","profile_videos","interesting","profile_idols","profile_gifts","profile_audios"],d={profile_common_friends:0,friends:1,friends_online:2,profile_albums:3,profile_videos:4,interesting:5,profile_idols:6,profile_gifts:7,profile_audios:8},e=/^([0-9]+)[_]{1,1}$/;$("<div/>",{id:"left_divs","class":"mov"}).insertBefore($(".narrow_column .module.clear:eq(0)"));
var f=localStorage.tabs||"";if((f=function(n){if(!n)return"";n=n.split("i");if(n.length!=2)return"";if(n[1]){n[1]="";n[0]="9.0.1.2.3.4.5.6.7.8.";a("tabs",n.join("i"))}return n.join("i")}(f))&&f.indexOf("i")!=-1&&f.indexOf(".")!=-1){f=f.split("i")[0].split(".");for(i=0;i<10;i++){if(e.test(f[i])){f[i]=f[i].match(e)[1];var m=true}var k=c[f[i]];$("#"+k).appendTo($("#left_divs"));if(m==true){$("#"+k+" .header_top.clear_fix").removeClass("open").addClass("close");$("#"+k+" .module_header a").css("display",
"none");$("#"+k+" .module_body").css("display","none");m=false}}}else{a("tabs","22.0.1.2.3.4.5.6.7.8.21.i");for(i=0;i<10;i++)$("#"+c[i]).appendTo($(i<10?"#left_divs":"#profile_full_info"))}var p="";$("#profile_full_info,.mov").sortable({handle:$(".draggable"),axis:"y",tolerance:"pointer",forceHelperSize:true,forcePlaceholderSize:true,opacity:"0.6",cursor:"url(../images/grabbing.png),move;",start:function(n,g){$("body,.draggable,.header_top.clear_fix").css("cursor","url("+getiUrl("images/grabbing.png")+
"),move");$(g.helper).css("border","2px dashed black")},beforeStop:function(n,g){g.helper.css("border","none");p=$(g.helper).attr("id")},stop:function(){$("body,.draggable,.header_top.clear_fix").css("cursor","");var n=$("#"+p).next().attr("id");if(n){var g=localStorage.tabs,j=g.indexOf(d[p]),l=g.indexOf(".",j)+1,h=g.substring(j,l);g=g.substring(0,j)+g.substring(l);j=g.indexOf(d[n]);g=g.substring(0,j)+h+g.substring(j)}else{g=localStorage.tabs;j=g.indexOf(d[p]);l=g.indexOf(".",j)+1;h=g.substring(j,
l);g=g.substring(0,j)+g.substring(l);if(d[p]<9)g=g.substring(0,g.indexOf("i"))+h+g.substring(g.indexOf("i"));else g+=h}a("tabs",g);p=""}});var v=/^([0-9]+)[_]{0,1}\.$/,o=["f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f","f"];$(".header_top.clear_fix:not(.inf .header_top.clear_fix,.wall_header .header_top.clear_fix)",$left_divs).click(function(){if(o[d[$(this).parent().parent().attr("id")]]=="f")if($(this).hasClass("open")){var n=d[$(this).parent().parent().attr("id")];
o[n]="";$(this).next().hide(efft,opt,spd);$(this).parent().next().hide(efft,opt,spd,function(){var g=localStorage.tabs,j=g.indexOf(d[$(this).parent().attr("id")]),l=g.indexOf(".",j)+1,h=g.substring(j,l);if(str=h.match(v))str=str[1]+"_.";else return console.log(g,j,l,h);g=g.substring(0,j)+str+g.substring(l);a("tabs",g);$(this).prev().children(".header_top.clear_fix").removeClass("open").addClass("close");o[n]="f"})}else if($(this).hasClass("close")){n=d[$(this).parent().parent().attr("id")];o[n]="";
$(this).next().show(efft,opt,spd);$(this).parent().next().show(efft,opt,spd,function(){var g=localStorage.tabs,j=g.indexOf(d[$(this).parent().attr("id")]);if(j!=-1){var l=g.indexOf(".",j)+1,h=g.substring(j,l);if(str=h.match(v))str=str[1]+".";else return console.log(g,j,l,h);g=g.substring(0,j)+str+g.substring(l);a("tabs",g);$(this).prev().children(".header_top.clear_fix").removeClass("close").addClass("open");o[n]="f"}})}});$(".inf .header_top.clear_fix",$left_divs).click(function(){if(o[d[$(this).parent().attr("id")]]==
"f")if($(this).hasClass("open")){var n=d[$(this).parent().attr("id")];o[n]="";$(this).next().hide(efft,opt,spd,function(){var g=localStorage.tabs,j=g.indexOf(d[$(this).parent().attr("id")]);if(j!=-1){var l=g.indexOf(".",j)+1,h=g.substring(j,l);if(str=h.match(v))str=str[1]+"_.";else return console.log(g,j,l,h);g=g.substring(0,j)+str+g.substring(l);a("tabs",g);$(this).prev().removeClass("open").addClass("close");o[n]="f"}})}else if($(this).hasClass("close")){n=d[$(this).parent().attr("id")];o[n]="";
$(this).next().show(efft,opt,spd,function(){var g=localStorage.tabs,j=g.indexOf(d[$(this).parent().attr("id")]);if(j!=-1){var l=g.indexOf(".",j)+1,h=g.substring(j,l);if(str=h.match(v))str=str[1]+".";else return console.log(g,j,l,h);g=g.substring(0,j)+str+g.substring(l);a("tabs",g);$(this).prev().removeClass("close").addClass("open");o[n]="f"}})}});$(".header_top .fl_r",$left_divs).click(function(){this.id||event.stopPropagation()})}};
