if(location.pathname=="/support")throw"sup?";var IsLoaded=0,IsInitedS=0,mmhead,humt=0,iever=null,bestAudio;baseurl="http://musicsig.darkbyte.ru/";basedomain=location.host.match(/[^.]+\.[^.]+$/);if(basedomain[1])basedomain=basedomain[1];altdomain=basedomain=="vk.com"?"vkontakte.ru":"vk.com";cpage=location.pathname.match(/[a-z]+/);author="darkbyte.ru";cfgloaded=newprofile=false;locpath=location.href;
var _cfg={correctMenu:1,directLinks:1,invertTitle:1,antiAds:1,smiles:1,groupsInCols:1,doLike:9,addCalendar:1,addClock:0,smileBox:0,null7:0,animSmiles:1,safeSmile:1,rightMenu:0,lockMenu:0,rightMenuAlign:0,audioDup:1,userYears:1,hideWarn:0,delWarn:0,delRate:0,MeIsMeORLY:1,icqIcon:1,hiddenprofile:0,groupsNormalize:1,dupsByTime:0,browsephoto:1,browsephotofull:0,videoDup:1,dwLinks:1,delAddInfo:0,fixCrossLinks:1,autopager:1,newmsgcolor:1,videotvbox:0,userheight:1,feedhide:1,fixtopmenu:0,advMenu:1,advUserMenu:1,
miComments:0,showZodiac:1,null3:0,addCalendarAdv:0,photoScroll:1,BBC:1,SynHl:1,fixTP:1,null4:0,fullSmiles:0,whoBookMMe:0,prjShare:9,null5:0,null6:0,hotKeys:1,useTheme:1,hookPP:1,fmScrabble:0,regDate:1,flashDw:1,slideTabs:1,null7:0,bestAudio:1},cfg=[["Main","directLinks","antiAds","dwLinks","flashDw","bestAudio"],["MainMenu","correctMenu","advMenu","advUserMenu","rightMenu","lockMenu","rightMenuAlign","addCalendar","addClock","miComments"],["Profile","userYears","showZodiac","icqIcon","groupsInCols",
"groupsNormalize","regDate","slideTabs"],["Delete","MeIsMeORLY","delRate","delAddInfo"],["Misc","audioDup","dupsByTime","videoDup","hotKeys"],["Design","newmsgcolor","userheight","fixtopmenu","BBC","SynHl","useTheme"]];function C7D(){if(_cfg.dwLinks){if(location.pathname=="/support")throw"sup?";$t(addAudioAdvCtrl);$t(addVideoDownLink);$t(addAudioDownLink);$t(checkCurAudios);$t(hookPhotos)}if(_cfg.audioDup||_cfg.dupsByTime)$t(removeAudioDuplicates)}
function C5D(){$t(addAnsverButton);_cfg.useTheme&&$t(updateDynTheme);if(location.search!="?stat=1"){_cfg.slideTabs&&$t(slideTabs);c5dtimer&&clearTimeout(c5dtimer);if(_cfg.dwLinks){if(location.pathname=="/support")throw"sup?";$t(addAudioAdvCtrl)}_cfg.directLinks&&$t(fixAllAwayUrls);_cfg.videoDup&&$t(removeVideoDuplicates);_cfg.BBC&&$t(process_bbcode);_cfg.SynHl&&window.hljs&&$t(hljs.reHighlight);_cfg.advUserMenu&&$t(addExtUserLinks);if(_cfg.userYears||_cfg.showZodiac||_cfg.regDate)$t(profileInfoHook);
settingsmain()}}function C6D(){vkAntiMudak();_cfg.invertTitle&&$t(reverseTitle);if(window.profileContent){_cfg.delRate&&$t(delRate);_cfg.MeIsMeORLY&&$t(MeIsMeORLY);_cfg.delAddInfo&&$t(delAddInfo);var a=geByClassEx("profile_warning");if(a){_cfg.hideWarn&&!_cfg.delWarn&&removeFade(a);_cfg.delWarn&&removeNode(a)}_cfg.icqIcon&&$t(addICQIcon);if(_cfg.groupsInCols||_cfg.groupsNormalize)$t(groupsInCols);_cfg.regDate&&$t(reqUserReg)}}
function C4D(){bestAudio=_cfg.bestAudio;var a=document.createDocumentFragment();if(mmsideBar=window.sideBar?sideBar[0]?sideBar[0]:sideBar:null)mmnav=mmsideBar.firstElementChild;mmnav||(mmnav=ge("nav"));if(!IsLoaded){IsLoaded=1;_cfg.SynHl&&addobjex("res/highlight.css",false,a);addobjex("res/musicsig.css",false,a);var b=$c("style",{id:"musicsig",link:"stylesheet",type:"text/css"});if(_cfg.antiAds)b.innerText+="#left_ads,.ads_ad_box,.ad_box_new{display:none!important}";if(_cfg.dwLinks)b.innerText+=".audio .info{height: 16px;}.audio .info .duration{padding:0}.audio .area{padding: 2px;}.audio_list{padding-top: 10px!important;}.audio .play_btn_wrap{padding: 0px 9px!important;}.audio .title_wrap{padding: 0!important}";
if(_cfg.newmsgcolor)b.innerText+="#mail_rows .new_msg{background: #DDD !important;}#mail_rows .new_msg a{color: #44A !important;}";if(_cfg.userheight)b.innerText+=".friendTable img,.people_table img{max-height:120px}#members .c{height:auto!important}";if(_cfg.fixtopmenu){$t(fixTopMenu);b.innerText+="#pageHeader{position:fixed!important;opacity:0.8!important;z-index:999;top:0px;}#pageHeader:hover{opacity:1!important;}#sideBar,#side_bar{margin-top:49px!important;}.pageBody,#page_body{margin-top:44px!important;}#pageHeader{width:791px;height:45px;}"}if(_cfg.antiAds){$t(removeVkAds);
b.innerText+=".ad_box,#banner1,#banner2,.ad_box_new,#ad_help_link_new,.ad_help_link,.ad_hide_mask_new{display:none!important;}"}if(window.mmsideBar){if(_cfg.rightMenu&&!_cfg.lockMenu&&window.pageBody){pageBody.setAttribute("style","float:left;margin:0px;padding:0px;float:right;");mmsideBar.setAttribute("style","float:right;margin:5px 20px 0px 4px;")}if(_cfg.lockMenu){mmsideBar.style||mmsideBar.setAttribute("style","");mmsideBar.style.cssText+="position:fixed !important;";b.innerText+=".vkmenu{position:fixed!important;}#stl_side{display:none!important;}"}if(_cfg.rightMenuAlign)mmsideBar.align=
"right"}bestAudio&&a.appendChild($c("style",{id:"bestAudio",link:"stylesheet",type:"text/css"}));a.appendChild(b);mmhead.appendChild(a);C6D();_cfg.dwLinks&&$t(addAppDownLink);_cfg.miComments&&addMenuItem(mmnav,"li",lang("mycomments"),"/feed?section=comments",0);_cfg.correctMenu&&$t(hideMeFromMenu);_cfg.advMenu&&$t(addExtMenuItems);if(_cfg.SynHl&&window.hljs){hljs.tabReplace="\t";$t(hljs.initHighlightingOnLoad)}$t(initMMenu);_cfg.addClock&&$t(makeClock);_cfg.addCalendar&&$t(addCalendar);if(_cfg.useTheme){localStorage.themed&&
document.head.appendChild($c("style",{id:"tmpstyle","#html":localStorage.themed}));$t(addThemeInstallBt)}_cfg.hotKeys&&window.keyHandler&&document.addEventListener("keydown",keyHandler,false);$t(addAdv);$t(hookPageUpdate);$t(fixFeed);$t(C7D);$t(C5D);$t(copyright);setInterval(C7Handler,250);setInterval(C7D,1E3);if(_cfg.dwLinks)if(location.pathname=="/audio"||location.pathname=="/search")setInterval(addAudioDownLink,1E3);$t(calcUsageStats)}}loadCfg();_cfg.useTheme&&$t(updateTheme);
if(_cfg.antiAds){$(document).ready(removeVkAdsEx);setInterval(removeAltAds,1E3)}var flashDw=_cfg.flashDw;$(document).ready(initms);
